-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.

/-!
# RIINA AntiJamming - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/domains/AntiJamming.v (25 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| JammerType | JammerType | OK |
| JamDetection | JamDetection | OK |
| AdaptAction | AdaptAction | OK |
| sequence_length_ok | sequence_length_ok | OK |
| dwell_time_bounded | dwell_time_bounded | OK |
| processing_gain_sufficient | processing_gain_sufficient | OK |
| jammer_overcome | jammer_overcome | OK |
| channels_diverse | channels_diverse | OK |
| detect_jamming | detect_jamming | OK |
| adaptation_applied | adaptation_applied | OK |
| power_increase_bounded | power_increase_bounded | OK |
| avoids_jammed | avoids_jammed | OK |
| rate_above_minimum | rate_above_minimum | OK |
| fec_gain_sufficient | fec_gain_sufficient | OK |
| switch_latency_ok | switch_latency_ok | OK |
| hops_synchronized | hops_synchronized | OK |
| key_valid | key_valid | OK |
| sweep_jammer_pattern | sweep_jammer_pattern | OK |
| silence_period_ok | silence_period_ok | OK |
| adaptation_fast_enough | adaptation_fast_enough | OK |
| quality_acceptable | quality_acceptable | OK |
| degradation_graceful | degradation_graceful | OK |
| fallback_bands_available | fallback_bands_available | OK |
| interference_localized | interference_localized | OK |
| paths_redundant | paths_redundant | OK |
| antijam_layers | antijam_layers | OK |
| jam_001_sequence_length | jam_001_sequence_length | OK |
| jam_002_dwell_bounded | jam_002_dwell_bounded | OK |
| jam_003_processing_gain | jam_003_processing_gain | OK |
| jam_004_code_length | jam_004_code_length | OK |
| jam_005_jammer_overcome | jam_005_jammer_overcome | OK |
| jam_006_channel_diversity | jam_006_channel_diversity | OK |
| jam_007_detection_threshold | jam_007_detection_threshold | OK |
| jam_008_no_false_positive | jam_008_no_false_positive | OK |
| jam_009_adaptation_improves | jam_009_adaptation_improves | OK |
| jam_010_power_bounded | jam_010_power_bounded | OK |
| jam_011_avoids_jammed | jam_011_avoids_jammed | OK |
| jam_012_rate_minimum | jam_012_rate_minimum | OK |
| jam_013_fec_gain | jam_013_fec_gain | OK |
| jam_014_switch_latency | jam_014_switch_latency | OK |
| jam_015_synchronized | jam_015_synchronized | OK |
| jam_016_key_required | jam_016_key_required | OK |
| jam_017_sweep_detected | jam_017_sweep_detected | OK |
| jam_018_reactive_mitigation | jam_018_reactive_mitigation | OK |
| jam_019_adaptation_speed | jam_019_adaptation_speed | OK |
| jam_020_quality_acceptable | jam_020_quality_acceptable | OK |
| jam_021_graceful_degradation | jam_021_graceful_degradation | OK |
| jam_022_fallback_available | jam_022_fallback_available | OK |
| jam_023_interference_localized | jam_023_interference_localized | OK |
| jam_024_redundant_paths | jam_024_redundant_paths | OK |
| jam_025_defense_in_depth | jam_025_defense_in_depth | OK |
-/

namespace RIINA.Domains.AntiJamming

/-- Coq compatibility shim: boolean negation -/
@[inline] private def negb (b : Bool) : Bool := !b
/-- Coq compatibility shim: boolean conjunction -/
@[inline] private def andb (a b : Bool) : Bool := a && b
/-- Coq compatibility shim: boolean disjunction -/
@[inline] private def orb (a b : Bool) : Bool := a || b
/-- Coq compatibility shim: list universal predicate -/
@[inline] private def forallb {α : Type} (f : α → Bool) (xs : List α) : Bool := xs.all f
/-- Coq compatibility shim: list existential predicate -/
@[inline] private def existsb {α : Type} (f : α → Bool) (xs : List α) : Bool := xs.any f
/-- Coq compatibility shim: list length alias -/
@[inline] private def length {α : Type} (xs : List α) : Nat := xs.length
/-- Coq compatibility shim: list head option -/
@[inline] private def hd_error {α : Type} (xs : List α) : Option α := xs.head?
/-- Coq compatibility shim: list find option -/
@[inline] private def find {α : Type} (p : α → Bool) (xs : List α) : Option α := xs.find? p
/-- Coq compatibility shim: pair first projection -/
@[inline] private def fst {α β : Type} (p : α × β) : α := p.1
/-- Coq compatibility shim: pair second projection -/
@[inline] private def snd {α β : Type} (p : α × β) : β := p.2

/-- JammerType (matches Coq: Inductive JammerType) -/
inductive JammerType where
  | ConstantJammer : JammerType
  | ReactiveJammer : JammerType
  | SweepJammer : JammerType
  | SmartJammer : JammerType
  deriving DecidableEq, Repr

/-- JamDetection (matches Coq: Inductive JamDetection) -/
inductive JamDetection where
  | NoJamming : JamDetection
  | SuspectedJamming : JamDetection
  | ConfirmedJamming : JamDetection
  deriving DecidableEq, Repr

/-- AdaptAction (matches Coq: Inductive AdaptAction) -/
inductive AdaptAction where
  | IncreasePower : AdaptAction
  | ChangeFrequency : AdaptAction
  | ReduceRate : AdaptAction
  | EnableFEC : AdaptAction
  | SwitchMode : AdaptAction
  deriving DecidableEq, Repr

/-- HoppingPattern record (matches Coq: Record HoppingPattern) -/
structure HoppingPattern where
  hop_sequence : List Nat
  hop_dwell_time : Nat
  deriving DecidableEq, Repr

/-- SpreadSpectrum record (matches Coq: Record SpreadSpectrum) -/
structure SpreadSpectrum where
  spread_code : List Nat
  spread_factor : Nat
  deriving DecidableEq, Repr

/-- sequence_length_ok (matches Coq: Definition sequence_length_ok) -/
def sequence_length_ok (pattern : HoppingPattern) (min_length : Nat) : Bool :=
  Nat.ble min_length (length pattern.hop_sequence)

/-- dwell_time_bounded (matches Coq: Definition dwell_time_bounded) -/
def dwell_time_bounded (pattern : HoppingPattern) (max_dwell : Nat) : Bool :=
  Nat.ble pattern.hop_dwell_time max_dwell

/-- processing_gain_sufficient (matches Coq: Definition processing_gain_sufficient) -/
def processing_gain_sufficient (ss : SpreadSpectrum) (min_gain : Nat) : Bool :=
  Nat.ble min_gain ss.spread_factor

/-- jammer_overcome (matches Coq: Definition jammer_overcome) -/
def jammer_overcome (jammer_power spread_gain signal_power : Nat) : Bool :=
  Nat.blt jammer_power (signal_power + spread_gain)

/-- channels_diverse (matches Coq: Definition channels_diverse) -/
def channels_diverse (pattern : HoppingPattern) (min_channels : Nat) : Prop :=
  length (pattern.hop_sequence.eraseDups) >= min_channels

/-- detect_jamming (matches Coq: Definition detect_jamming) -/
def detect_jamming (snr threshold : Nat) : JamDetection :=
  if Nat.blt snr (threshold / 2) then JamDetection.ConfirmedJamming
  else if Nat.blt snr threshold then JamDetection.SuspectedJamming
  else JamDetection.NoJamming

/-- adaptation_applied (matches Coq: Definition adaptation_applied) -/
def adaptation_applied (before after : Nat) (_action : AdaptAction) : Prop :=
  after >= before

/-- power_increase_bounded (matches Coq: Definition power_increase_bounded) -/
def power_increase_bounded (current max_power : Nat) : Bool :=
  Nat.ble current max_power

/-- avoids_jammed (matches Coq: Definition avoids_jammed) -/
def avoids_jammed (_new_channel : List Nat) (jammed_channels : List Nat) (channel : Nat) : Bool :=
  negb (existsb (fun j => Nat.beq j channel) jammed_channels)

/-- rate_above_minimum (matches Coq: Definition rate_above_minimum) -/
def rate_above_minimum (current min_rate : Nat) : Bool :=
  Nat.ble min_rate current

/-- fec_gain_sufficient (matches Coq: Definition fec_gain_sufficient) -/
def fec_gain_sufficient (redundancy min_gain : Nat) : Bool :=
  Nat.ble min_gain redundancy

/-- switch_latency_ok (matches Coq: Definition switch_latency_ok) -/
def switch_latency_ok (latency max_latency : Nat) : Bool :=
  Nat.ble latency max_latency

/-- hops_synchronized (matches Coq: Definition hops_synchronized) -/
def hops_synchronized (sender_channel receiver_channel : Nat) : Bool :=
  Nat.beq sender_channel receiver_channel

/-- key_valid (matches Coq: Definition key_valid) -/
def key_valid (provided_key expected_key : Nat) : Bool :=
  Nat.beq provided_key expected_key

/-- sweep_jammer_pattern (matches Coq: Definition sweep_jammer_pattern) -/
def sweep_jammer_pattern (affected : List Nat) (threshold : Nat) : Bool :=
  Nat.ble threshold (length affected)

/-- silence_period_ok (matches Coq: Definition silence_period_ok) -/
def silence_period_ok (silence min_silence : Nat) : Bool :=
  Nat.ble min_silence silence

/-- adaptation_fast_enough (matches Coq: Definition adaptation_fast_enough) -/
def adaptation_fast_enough (adapt_time max_time : Nat) : Bool :=
  Nat.ble adapt_time max_time

/-- quality_acceptable (matches Coq: Definition quality_acceptable) -/
def quality_acceptable (snr min_snr : Nat) : Bool :=
  Nat.ble min_snr snr

/-- degradation_graceful (matches Coq: Definition degradation_graceful) -/
def degradation_graceful (service_level min_level : Nat) : Bool :=
  Nat.ble min_level service_level

/-- fallback_bands_available (matches Coq: Definition fallback_bands_available) -/
def fallback_bands_available (bands : List Nat) (min_bands : Nat) : Bool :=
  Nat.ble min_bands (length bands)

/-- interference_localized (matches Coq: Definition interference_localized) -/
def interference_localized (sources : List Nat) : Prop :=
  length sources > 0

/-- paths_redundant (matches Coq: Definition paths_redundant) -/
def paths_redundant (paths min_paths : Nat) : Bool :=
  Nat.ble min_paths paths

/-- antijam_layers (matches Coq: Definition antijam_layers) -/
def antijam_layers (hopping spread detect adapt : Bool) : Bool :=
  andb hopping (andb spread (andb detect adapt))

/-- jam_001_sequence_length (matches Coq) -/
theorem jam_001_sequence_length : ∀ (pattern : HoppingPattern) (min_length : Nat),
    sequence_length_ok pattern min_length = true → min_length ≤ length pattern.hop_sequence := by
  intro pattern min_length h
  simp [sequence_length_ok, Nat.ble_eq] at h
  exact h

/-- jam_002_dwell_bounded (matches Coq) -/
theorem jam_002_dwell_bounded : ∀ (pattern : HoppingPattern) (max_dwell : Nat),
    dwell_time_bounded pattern max_dwell = true → pattern.hop_dwell_time ≤ max_dwell := by
  intro pattern max_dwell h
  simp [dwell_time_bounded, Nat.ble_eq] at h
  exact h

/-- jam_003_processing_gain (matches Coq) -/
theorem jam_003_processing_gain : ∀ (ss : SpreadSpectrum) (min_gain : Nat),
    processing_gain_sufficient ss min_gain = true → min_gain ≤ ss.spread_factor := by
  intro ss min_gain h
  simp [processing_gain_sufficient, Nat.ble_eq] at h
  exact h

/-- jam_004_code_length (matches Coq) -/
theorem jam_004_code_length : ∀ (ss : SpreadSpectrum),
    length ss.spread_code > 0 → length ss.spread_code > 0 := by
  intro _ h; exact h

/-- jam_005_jammer_overcome (matches Coq) -/
theorem jam_005_jammer_overcome : ∀ (jammer_power spread_gain signal_power : Nat),
    jammer_overcome jammer_power spread_gain signal_power = true →
    jammer_power < signal_power + spread_gain := by
  intro jp sg sp h
  simp [jammer_overcome, Nat.blt_eq] at h
  exact h

/-- jam_006_channel_diversity (matches Coq) -/
theorem jam_006_channel_diversity : ∀ (pattern : HoppingPattern) (min_channels : Nat),
    channels_diverse pattern min_channels →
    length (pattern.hop_sequence.eraseDups) ≥ min_channels := by
  intro _ _ h; exact h

/-- jam_007_detection_threshold (matches Coq) -/
theorem jam_007_detection_threshold : ∀ (snr threshold : Nat),
    snr < threshold / 2 → detect_jamming snr threshold = JamDetection.ConfirmedJamming := by
  intro snr threshold h
  simp [detect_jamming, Nat.blt_eq, h]

/-- jam_008_no_false_positive (matches Coq) -/
theorem jam_008_no_false_positive : ∀ (snr threshold : Nat),
    snr ≥ threshold → detect_jamming snr threshold = JamDetection.NoJamming := by
  intro snr threshold h
  unfold detect_jamming
  have h1 : ¬(snr < threshold / 2) := by omega
  have h2 : ¬(snr < threshold) := by omega
  simp [Nat.blt_eq, h1, h2]

/-- jam_009_adaptation_improves (matches Coq) -/
theorem jam_009_adaptation_improves : ∀ (before after : Nat) (action : AdaptAction),
    adaptation_applied before after action → after ≥ before := by
  intro _ _ _ h; exact h

/-- jam_010_power_bounded (matches Coq) -/
theorem jam_010_power_bounded : ∀ (current max_power : Nat),
    power_increase_bounded current max_power = true → current ≤ max_power := by
  intro current max_power h
  simp [power_increase_bounded, Nat.ble_eq] at h
  exact h

/-- jam_011_avoids_jammed (matches Coq) -/
theorem jam_011_avoids_jammed : ∀ (channel : Nat) (jammed_channels : List Nat),
    avoids_jammed [] jammed_channels channel = true →
    ¬(channel ∈ jammed_channels) ∨ (channel ∈ jammed_channels) := by
  intro channel jammed_channels _
  by_cases hm : channel ∈ jammed_channels
  · exact Or.inr hm
  · exact Or.inl hm

/-- jam_012_rate_minimum (matches Coq) -/
theorem jam_012_rate_minimum : ∀ (current min_rate : Nat),
    rate_above_minimum current min_rate = true → min_rate ≤ current := by
  intro current min_rate h
  simp [rate_above_minimum, Nat.ble_eq] at h
  exact h

/-- jam_013_fec_gain (matches Coq) -/
theorem jam_013_fec_gain : ∀ (redundancy min_gain : Nat),
    fec_gain_sufficient redundancy min_gain = true → min_gain ≤ redundancy := by
  intro redundancy min_gain h
  simp [fec_gain_sufficient, Nat.ble_eq] at h
  exact h

/-- jam_014_switch_latency (matches Coq) -/
theorem jam_014_switch_latency : ∀ (latency max_latency : Nat),
    switch_latency_ok latency max_latency = true → latency ≤ max_latency := by
  intro latency max_latency h
  simp [switch_latency_ok, Nat.ble_eq] at h
  exact h

/-- jam_015_synchronized (matches Coq) -/
theorem jam_015_synchronized : ∀ (sender receiver : Nat),
    hops_synchronized sender receiver = true → sender = receiver := by
  intro sender receiver h
  simp [hops_synchronized, Nat.beq_eq] at h
  exact h

/-- jam_016_key_required (matches Coq) -/
theorem jam_016_key_required : ∀ (provided expected : Nat),
    key_valid provided expected = true → provided = expected := by
  intro provided expected h
  simp [key_valid, Nat.beq_eq] at h
  exact h

/-- jam_017_sweep_detected (matches Coq) -/
theorem jam_017_sweep_detected : ∀ (affected : List Nat) (threshold : Nat),
    sweep_jammer_pattern affected threshold = true → threshold ≤ length affected := by
  intro affected threshold h
  simp [sweep_jammer_pattern, Nat.ble_eq] at h
  exact h

/-- jam_018_reactive_mitigation (matches Coq) -/
theorem jam_018_reactive_mitigation : ∀ (silence min_silence : Nat),
    silence_period_ok silence min_silence = true → min_silence ≤ silence := by
  intro silence min_silence h
  simp [silence_period_ok, Nat.ble_eq] at h
  exact h

/-- jam_019_adaptation_speed (matches Coq) -/
theorem jam_019_adaptation_speed : ∀ (adapt_time max_time : Nat),
    adaptation_fast_enough adapt_time max_time = true → adapt_time ≤ max_time := by
  intro adapt_time max_time h
  simp [adaptation_fast_enough, Nat.ble_eq] at h
  exact h

/-- jam_020_quality_acceptable (matches Coq) -/
theorem jam_020_quality_acceptable : ∀ (snr min_snr : Nat),
    quality_acceptable snr min_snr = true → min_snr ≤ snr := by
  intro snr min_snr h
  simp [quality_acceptable, Nat.ble_eq] at h
  exact h

/-- jam_021_graceful_degradation (matches Coq) -/
theorem jam_021_graceful_degradation : ∀ (service_level min_level : Nat),
    degradation_graceful service_level min_level = true → min_level ≤ service_level := by
  intro service_level min_level h
  simp [degradation_graceful, Nat.ble_eq] at h
  exact h

/-- jam_022_fallback_available (matches Coq) -/
theorem jam_022_fallback_available : ∀ (bands : List Nat) (min_bands : Nat),
    fallback_bands_available bands min_bands = true → min_bands ≤ length bands := by
  intro bands min_bands h
  simp [fallback_bands_available, Nat.ble_eq] at h
  exact h

/-- jam_023_interference_localized (matches Coq) -/
theorem jam_023_interference_localized : ∀ (sources : List Nat),
    interference_localized sources → length sources > 0 := by
  intro _ h; exact h

/-- jam_024_redundant_paths (matches Coq) -/
theorem jam_024_redundant_paths : ∀ (paths min_paths : Nat),
    paths_redundant paths min_paths = true → min_paths ≤ paths := by
  intro paths min_paths h
  simp [paths_redundant, Nat.ble_eq] at h
  exact h

/-- jam_025_defense_in_depth (matches Coq) -/
theorem jam_025_defense_in_depth : ∀ h s d a,
    antijam_layers h s d a = true → h = true ∧ s = true ∧ d = true ∧ a = true := by
  intro h s d a hyp
  simp [antijam_layers, andb] at hyp
  exact hyp

end RIINA.Domains.AntiJamming
