-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.

/-!
# RIINA DELTA001_VerifiedDistribution - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/domains/DELTA001_VerifiedDistribution.v (32 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| Role | Role | OK |
| BFTPhase | BFTPhase | OK |
| LogEntry | LogEntry | OK |
| RaftNode | RaftNode | OK |
| RaftCluster | RaftCluster | OK |
| BFTMessage | BFTMessage | OK |
| BFTState | BFTState | OK |
| HashRing | HashRing | OK |
| is_quorum | is_quorum | OK |
| voted_for_in_term | voted_for_in_term | OK |
| count_votes | count_votes | OK |
| log_entry_at | log_entry_at | OK |
| logs_match_at | logs_match_at | OK |
| entry_committed | entry_committed | OK |
| bft_quorum | bft_quorum | OK |
| bft_valid | bft_valid | OK |
| gc_increment | gc_increment | OK |
| gc_value | gc_value | OK |
| gc_merge | gc_merge | OK |
| gs_add | gs_add | OK |
| gs_merge | gs_merge | OK |
| gs_member | gs_member | OK |
| ring_lookup | ring_lookup | OK |
| ring_add_node | ring_add_node | OK |
| ring_remove_node | ring_remove_node | OK |
| DELTA_001_01_quorum_intersection | DELTA_001_01_quorum_intersection | OK |
| DELTA_001_02_single_vote_per_term | DELTA_001_02_single_vote_per_term | OK |
| DELTA_001_03_log_matching_reflexive | DELTA_001_03_log_matching_reflexive | OK |
| DELTA_001_04_committed_requires_quorum | DELTA_001_04_committed_requires_quorum | OK |
| DELTA_001_05_empty_log_no_commit | DELTA_001_05_empty_log_no_commit | OK |
| DELTA_001_06_leader_append_only | DELTA_001_06_leader_append_only | OK |
| DELTA_001_07_term_monotonic | DELTA_001_07_term_monotonic | OK |
| DELTA_001_08_entry_at_deterministic | DELTA_001_08_entry_at_deterministic | OK |
| DELTA_001_09_log_prefix_match | DELTA_001_09_log_prefix_match | OK |
| DELTA_001_10_quorum_nonempty | DELTA_001_10_quorum_nonempty | OK |
| DELTA_002_01_bft_bound | DELTA_002_01_bft_bound | OK |
| DELTA_002_02_bft_quorum_sufficient | DELTA_002_02_bft_quorum_sufficient | OK |
| DELTA_002_03_bft_two_quorums_overlap | DELTA_002_03_bft_two_quorums_overlap | OK |
| DELTA_002_04_correct_majority | DELTA_002_04_correct_majority | OK |
| DELTA_002_05_bft_f_zero | DELTA_002_05_bft_f_zero | OK |
| DELTA_002_06_bft_phases_ordered | DELTA_002_06_bft_phases_ordered | OK |
| DELTA_003_01_gc_merge_comm | DELTA_003_01_gc_merge_comm | OK |
| DELTA_003_02_gc_merge_assoc | DELTA_003_02_gc_merge_assoc | OK |
| DELTA_003_03_gc_merge_idempotent | DELTA_003_03_gc_merge_idempotent | OK |
| DELTA_003_04_gc_value_nonneg | DELTA_003_04_gc_value_nonneg | OK |
| fold_left_add_mono | fold_left_add_mono | OK |
| DELTA_003_05_gc_merge_monotone | DELTA_003_05_gc_merge_monotone | OK |
| DELTA_003_06_gs_add_member | DELTA_003_06_gs_add_member | OK |
| DELTA_003_07_gs_add_preserves | DELTA_003_07_gs_add_preserves | OK |
| DELTA_003_08_gs_merge_contains_left | DELTA_003_08_gs_merge_contains_left | OK |
| DELTA_003_09_gs_add_idempotent | DELTA_003_09_gs_add_idempotent | OK |
| DELTA_003_10_gc_empty_zero | DELTA_003_10_gc_empty_zero | OK |
| DELTA_004_01_ring_add_increases | DELTA_004_01_ring_add_increases | OK |
| DELTA_004_02_ring_remove_decreases | DELTA_004_02_ring_remove_decreases | OK |
| DELTA_004_03_ring_size_preserved_add | DELTA_004_03_ring_size_preserved_add | OK |
| DELTA_004_04_ring_size_preserved_remove | DELTA_004_04_ring_size_preserved_remove | OK |
| DELTA_004_05_empty_ring_no_lookup | DELTA_004_05_empty_ring_no_lookup | OK |
-/

namespace RIINA.Domains.DELTA001_VerifiedDistribution

-- Type aliases matching Coq definitions
abbrev Term := Nat
abbrev NodeId := Nat
abbrev GCounter := List Nat
abbrev GSet := List Nat

/-- Role (matches Coq: Inductive Role) -/
inductive Role where
  | Follower : Role
  | Candidate : Role
  | Leader : Role
  deriving DecidableEq, Repr

/-- BFTPhase (matches Coq: Inductive BFTPhase) -/
inductive BFTPhase where
  | PrePrepare : BFTPhase
  | Prepare : BFTPhase
  | Commit : BFTPhase
  | Reply : BFTPhase
  deriving DecidableEq, Repr

/-- LogEntry (matches Coq: Record LogEntry) -/
structure LogEntry where
  entry_term : Term
  entry_index : Nat
  entry_command : Nat
  deriving DecidableEq, Repr
/-- Coq constructor alias for LogEntry. -/
abbrev mkLogEntry := LogEntry.mk

/-- RaftNode (matches Coq: Record RaftNode) -/
structure RaftNode where
  node_id : NodeId
  node_term : Term
  node_role : Role
  node_log : List LogEntry
  node_voted_for : Option NodeId
  node_commit_index : Nat
  deriving DecidableEq, Repr
/-- Coq constructor alias for RaftNode. -/
abbrev mkRaftNode := RaftNode.mk

/-- RaftCluster (matches Coq: Record RaftCluster) -/
structure RaftCluster where
  cluster_nodes : List RaftNode
  cluster_size : Nat
  deriving DecidableEq, Repr
/-- Coq constructor alias for RaftCluster. -/
abbrev mkCluster := RaftCluster.mk

/-- BFTMessage (matches Coq: Record BFTMessage) -/
structure BFTMessage where
  bft_phase : BFTPhase
  bft_view : Nat
  bft_seq : Nat
  bft_digest : Nat
  bft_sender : NodeId
  deriving DecidableEq, Repr
/-- Coq constructor alias for BFTMessage. -/
abbrev mkBFTMsg := BFTMessage.mk

/-- BFTState (matches Coq: Record BFTState) -/
structure BFTState where
  bft_n : Nat
  bft_f : Nat
  bft_correct : List NodeId
  bft_faulty : List NodeId
  deriving DecidableEq, Repr
/-- Coq constructor alias for BFTState. -/
abbrev mkBFTState := BFTState.mk

/-- HashRing (matches Coq: Record HashRing) -/
structure HashRing where
  ring_nodes : List (Nat × NodeId)
  ring_size : Nat
  deriving DecidableEq, Repr
/-- Coq constructor alias for HashRing. -/
abbrev mkHashRing := HashRing.mk

/-- is_quorum (matches Coq: Definition is_quorum) -/
def is_quorum (votes : Nat) (total : Nat) : Bool :=
  Nat.blt total (2 * votes)

/-- voted_for_in_term (matches Coq: Definition voted_for_in_term) -/
def voted_for_in_term (node : RaftNode) (candidate : NodeId) (_term : Term) : Bool :=
  match node.node_voted_for with
  | some c => Nat.beq c candidate
  | none => false

/-- count_votes (matches Coq: Definition count_votes) -/
def count_votes (nodes : List RaftNode) (candidate : NodeId) (term : Term) : Nat :=
  (nodes.filter (fun n => voted_for_in_term n candidate term)).length

/-- log_entry_at (matches Coq: Definition log_entry_at) -/
def log_entry_at (log : List LogEntry) (idx : Nat) : Option LogEntry :=
  log.get? idx

/-- logs_match_at (matches Coq: Definition logs_match_at) -/
def logs_match_at (log1 log2 : List LogEntry) (idx : Nat) : Prop :=
  ∀ e1 e2,
    log_entry_at log1 idx = some e1 →
    log_entry_at log2 idx = some e2 →
    e1.entry_term = e2.entry_term →
    e1.entry_command = e2.entry_command

/-- entry_committed (matches Coq: Definition entry_committed) -/
def entry_committed (cluster : RaftCluster) (idx : Nat) : Bool :=
  let matching := cluster.cluster_nodes.filter (fun n => Nat.blt idx n.node_log.length)
  is_quorum matching.length cluster.cluster_size

/-- bft_quorum (matches Coq: Definition bft_quorum) -/
def bft_quorum (state : BFTState) : Nat :=
  2 * state.bft_f + 1

/-- bft_valid (matches Coq: Definition bft_valid) -/
def bft_valid (state : BFTState) : Bool :=
  Nat.blt (3 * state.bft_f) state.bft_n

/-- gc_increment (matches Coq: Definition gc_increment) -/
def gc_increment (gc : GCounter) (node : Nat) : GCounter :=
  ((List.range gc.length).zip gc).map
    (fun p => if Nat.beq p.1 node then p.2 + 1 else p.2)

/-- gc_value (matches Coq: Definition gc_value) -/
def gc_value (gc : GCounter) : Nat :=
  gc.foldl Nat.add 0

/-- gc_merge (matches Coq: Definition gc_merge) -/
def gc_merge (a b : GCounter) : GCounter :=
  (List.zip a b).map (fun p => Nat.max p.1 p.2)

/-- gc_merge is equivalent to List.zipWith Nat.max -/
private theorem gc_merge_eq_zipWith (a b : GCounter) :
    gc_merge a b = List.zipWith Nat.max a b := by
  simp only [gc_merge, List.zip]
  induction a generalizing b with
  | nil => simp [List.zipWith]
  | cons x xs ih =>
    cases b with
    | nil => simp [List.zipWith]
    | cons y ys =>
      simp only [List.zipWith_cons_cons, List.map_cons]
      congr 1
      exact ih ys

/-- gs_add (matches Coq: Definition gs_add) -/
def gs_add (s : GSet) (v : Nat) : GSet :=
  if s.any (Nat.beq v) then s else v :: s

/-- gs_merge (matches Coq: Definition gs_merge) -/
def gs_merge (a b : GSet) : GSet :=
  b.foldl (fun acc v => gs_add acc v) a

/-- gs_member (matches Coq: Definition gs_member) -/
def gs_member (s : GSet) (v : Nat) : Bool :=
  s.any (Nat.beq v)

/-- ring_lookup (matches Coq: Definition ring_lookup) -/
def ring_lookup (ring : HashRing) (_key : Nat) : Option NodeId :=
  match ring.ring_nodes with
  | [] => none
  | (_, n) :: _ => some n

/-- ring_add_node (matches Coq: Definition ring_add_node) -/
def ring_add_node (ring : HashRing) (pos : Nat) (node : NodeId) : HashRing :=
  { ring_nodes := (pos, node) :: ring.ring_nodes,
    ring_size := ring.ring_size }

/-- ring_remove_node (matches Coq: Definition ring_remove_node) -/
def ring_remove_node (ring : HashRing) (node : NodeId) : HashRing :=
  { ring_nodes := ring.ring_nodes.filter (fun p => !(Nat.beq p.2 node)),
    ring_size := ring.ring_size }

-- ===============================================================================
-- PROOFS: RAFT CONSENSUS (10 theorems)
-- ===============================================================================

/-- DELTA_001_01_quorum_intersection (matches Coq) -/
theorem DELTA_001_01_quorum_intersection :
    ∀ (n q1 q2 : Nat), is_quorum q1 n = true → is_quorum q2 n = true → q1 + q2 > n := by
  intro n q1 q2 h1 h2
  simp [is_quorum, Nat.blt] at h1 h2
  omega

/-- DELTA_001_02_single_vote_per_term (matches Coq) -/
theorem DELTA_001_02_single_vote_per_term :
    ∀ (node : RaftNode) (c1 c2 : NodeId) (term : Term),
    voted_for_in_term node c1 term = true →
    voted_for_in_term node c2 term = true → c1 = c2 := by
  intro node c1 c2 term h1 h2
  simp [voted_for_in_term] at h1 h2
  split at h1
  · split at h2
    · have e1 := Nat.eq_of_beq_eq_true h1
      have e2 := Nat.eq_of_beq_eq_true h2
      rename_i c1v hc1 _ c2v hc2
      rw [hc1] at hc2
      have := Option.some.inj hc2
      subst this; subst e1; subst e2; rfl
    · contradiction
  · contradiction

/-- DELTA_001_03_log_matching_reflexive (matches Coq) -/
theorem DELTA_001_03_log_matching_reflexive :
    ∀ (log : List LogEntry) (idx : Nat), logs_match_at log log idx := by
  intro log idx e1 e2 h1 h2 _
  rw [h1] at h2
  exact (Option.some.inj h2) ▸ rfl

/-- DELTA_001_04_committed_requires_quorum (matches Coq) -/
theorem DELTA_001_04_committed_requires_quorum :
    ∀ (cluster : RaftCluster) (idx : Nat),
    entry_committed cluster idx = true →
    let matching := cluster.cluster_nodes.filter (fun n => Nat.blt idx n.node_log.length)
    is_quorum matching.length cluster.cluster_size = true := by
  intro cluster idx h
  exact h

/-- DELTA_001_05_empty_log_no_commit (matches Coq) -/
theorem DELTA_001_05_empty_log_no_commit :
    ∀ (cluster : RaftCluster) (idx : Nat),
    (∀ n, n ∈ cluster.cluster_nodes → n.node_log = []) →
    idx > 0 → entry_committed cluster idx = false := by
  intro cluster idx hall hidx
  unfold entry_committed
  suffices hfilt : cluster.cluster_nodes.filter (fun n => Nat.blt idx n.node_log.length) = [] by
    simp only [hfilt]
    simp [is_quorum, Nat.blt, Nat.ble]
  rw [List.filter_eq_nil_iff]
  intro n hn
  have hlog := hall n hn
  simp [hlog, Nat.blt, Nat.ble]

/-- DELTA_001_06_leader_append_only (matches Coq) -/
theorem DELTA_001_06_leader_append_only :
    ∀ (leader : RaftNode) (entry : LogEntry),
    leader.node_role = Role.Leader →
    let log' := leader.node_log ++ [entry]
    log'.length = leader.node_log.length + 1 := by
  intro leader entry _
  simp [List.length_append]

/-- DELTA_001_07_term_monotonic (matches Coq) -/
theorem DELTA_001_07_term_monotonic : ∀ (t1 t2 : Nat), t1 < t2 → t1 ≠ t2 := by
  omega

/-- DELTA_001_08_entry_at_deterministic (matches Coq) -/
theorem DELTA_001_08_entry_at_deterministic :
    ∀ (log : List LogEntry) (idx : Nat) (e1 e2 : LogEntry),
    log_entry_at log idx = some e1 →
    log_entry_at log idx = some e2 → e1 = e2 := by
  intro log idx e1 e2 h1 h2
  rw [h1] at h2
  exact Option.some.inj h2

/-- DELTA_001_09_log_prefix_match (matches Coq) -/
theorem DELTA_001_09_log_prefix_match :
    ∀ (log1 log2 : List LogEntry) (idx : Nat) (e1 e2 : LogEntry),
    log_entry_at log1 idx = some e1 →
    log_entry_at log2 idx = some e2 →
    e1.entry_term = e2.entry_term →
    e1.entry_index = e2.entry_index →
    e1.entry_command = e2.entry_command →
    logs_match_at log1 log2 idx := by
  intro log1 log2 idx e1 e2 h1 h2 _ _ hcmd e1' e2' h1' h2' _
  rw [h1] at h1'
  rw [h2] at h2'
  have := Option.some.inj h1'
  have := Option.some.inj h2'
  subst_vars
  exact hcmd

/-- DELTA_001_10_quorum_nonempty (matches Coq) -/
theorem DELTA_001_10_quorum_nonempty :
    ∀ (n votes : Nat), is_quorum votes n = true → votes > 0 := by
  intro n votes h
  simp [is_quorum, Nat.blt] at h
  omega

-- ===============================================================================
-- PROOFS: BFT SAFETY (6 theorems)
-- ===============================================================================

/-- DELTA_002_01_bft_bound (matches Coq) -/
theorem DELTA_002_01_bft_bound :
    ∀ (state : BFTState), bft_valid state = true → state.bft_n ≥ 3 * state.bft_f + 1 := by
  intro state h
  simp [bft_valid, Nat.blt] at h
  omega

/-- DELTA_002_02_bft_quorum_sufficient (matches Coq) -/
theorem DELTA_002_02_bft_quorum_sufficient :
    ∀ (state : BFTState), bft_valid state = true → bft_quorum state ≤ state.bft_n := by
  intro state h
  simp [bft_valid, Nat.blt] at h
  simp [bft_quorum]
  omega

/-- DELTA_002_03_bft_two_quorums_overlap (matches Coq) -/
theorem DELTA_002_03_bft_two_quorums_overlap :
    ∀ (state : BFTState), bft_valid state = true →
    state.bft_n = 3 * state.bft_f + 1 →
    2 * bft_quorum state > state.bft_n := by
  intro state _ heq
  simp [bft_quorum, heq]
  omega

/-- DELTA_002_04_correct_majority (matches Coq) -/
theorem DELTA_002_04_correct_majority :
    ∀ (state : BFTState), bft_valid state = true →
    state.bft_correct.length + state.bft_faulty.length = state.bft_n →
    state.bft_faulty.length ≤ state.bft_f →
    state.bft_correct.length > state.bft_f := by
  intro state hv hsum hfaulty
  simp [bft_valid, Nat.blt] at hv
  omega

/-- DELTA_002_05_bft_f_zero (matches Coq) -/
theorem DELTA_002_05_bft_f_zero :
    ∀ (state : BFTState), state.bft_f = 0 → bft_quorum state = 1 := by
  intro state h
  simp [bft_quorum, h]

/-- DELTA_002_06_bft_phases_ordered (matches Coq) -/
theorem DELTA_002_06_bft_phases_ordered : ∀ (_p1 _p2 : BFTPhase), True := by
  intro _ _
  trivial

-- ===============================================================================
-- PROOFS: CRDT PROPERTIES (10 theorems)
-- ===============================================================================

/-- DELTA_003_01_gc_merge_comm (matches Coq) -/
theorem DELTA_003_01_gc_merge_comm :
    ∀ (a b : GCounter), a.length = b.length → gc_merge a b = gc_merge b a := by
  intro a b h
  simp only [gc_merge, List.zip]
  induction a generalizing b with
  | nil =>
    cases b with
    | nil => rfl
    | cons _ _ => simp at h
  | cons x xs ih =>
    cases b with
    | nil => simp at h
    | cons y ys =>
      simp only [List.zipWith_cons_cons, List.map_cons]
      congr 1
      · exact Nat.max_comm x y
      · exact ih ys (by simp at h; exact h)

/-- DELTA_003_02_gc_merge_assoc (matches Coq) -/
theorem DELTA_003_02_gc_merge_assoc :
    ∀ (a b c : GCounter), a.length = b.length → b.length = c.length →
    gc_merge (gc_merge a b) c = gc_merge a (gc_merge b c) := by
  intro a b c hab hbc
  simp only [gc_merge_eq_zipWith]
  induction a generalizing b c with
  | nil =>
    cases b with
    | nil => cases c <;> simp [List.zipWith]
    | cons _ _ => simp at hab
  | cons x xs ih =>
    cases b with
    | nil => simp at hab
    | cons y ys =>
      cases c with
      | nil => simp at hbc
      | cons z zs =>
        simp only [List.zipWith_cons_cons]
        congr 1
        · exact Nat.max_assoc x y z
        · exact ih ys zs (by simp at hab; exact hab) (by simp at hbc; exact hbc)

/-- DELTA_003_03_gc_merge_idempotent (matches Coq) -/
theorem DELTA_003_03_gc_merge_idempotent : ∀ (a : GCounter), gc_merge a a = a := by
  intro a
  simp only [gc_merge, List.zip, List.zipWith_same, List.map_map, Function.comp]
  induction a with
  | nil => rfl
  | cons x xs ih => simp [Nat.max_self, ih]

/-- DELTA_003_04_gc_value_nonneg (matches Coq) -/
theorem DELTA_003_04_gc_value_nonneg : ∀ (gc : GCounter), gc_value gc ≥ 0 := by
  intro _
  omega

/-- fold_left_add_mono (matches Coq) -/
theorem fold_left_add_mono :
    ∀ (l : List Nat) (acc1 acc2 : Nat), acc1 ≤ acc2 →
    l.foldl Nat.add acc1 ≤ l.foldl Nat.add acc2 := by
  intro l
  induction l with
  | nil => intro _ _ h; exact h
  | cons x xs ih =>
    intro acc1 acc2 h
    simp [List.foldl]
    exact ih _ _ (Nat.add_le_add_right h x)

/-- Helper for gc_merge_monotone -/
private theorem gc_merge_mono_aux (a b : GCounter) (hab : a.length = b.length) (acc : Nat) :
    a.foldl Nat.add acc ≤ (gc_merge a b).foldl Nat.add acc := by
  simp only [gc_merge, List.zip]
  induction a generalizing b acc with
  | nil =>
    cases b with
    | nil => simp [List.zipWith, List.foldl]
    | cons _ _ => simp at hab
  | cons x xs ih =>
    cases b with
    | nil => simp at hab
    | cons y ys =>
      simp only [List.zipWith_cons_cons, List.map_cons, List.foldl]
      have hlen : xs.length = ys.length := by simp at hab; exact hab
      have hle : acc + x ≤ acc + Nat.max x y := Nat.add_le_add_left (Nat.le_max_left x y) acc
      exact Nat.le_trans (ih ys hlen (acc + x)) (fold_left_add_mono _ _ _ hle)

/-- DELTA_003_05_gc_merge_monotone (matches Coq) -/
theorem DELTA_003_05_gc_merge_monotone :
    ∀ (a b : GCounter), a.length = b.length → gc_value (gc_merge a b) ≥ gc_value a := by
  intro a b h
  exact gc_merge_mono_aux a b h 0

/-- DELTA_003_06_gs_add_member (matches Coq) -/
theorem DELTA_003_06_gs_add_member : ∀ (s : GSet) (v : Nat), gs_member (gs_add s v) v = true := by
  intro s v
  unfold gs_add
  split
  · next h => exact h
  · simp [gs_member, List.any_cons, Nat.beq_refl]

/-- DELTA_003_07_gs_add_preserves (matches Coq) -/
theorem DELTA_003_07_gs_add_preserves :
    ∀ (s : GSet) (v v' : Nat), gs_member s v' = true → gs_member (gs_add s v) v' = true := by
  intro s v v' h
  unfold gs_add gs_member at *
  split
  · exact h
  · rw [List.any_cons]
    rw [Bool.or_eq_true]
    right
    exact h

/-- DELTA_003_08_gs_merge_contains_left (matches Coq) -/
theorem DELTA_003_08_gs_merge_contains_left :
    ∀ (a b : GSet) (v : Nat), gs_member a v = true → gs_member (gs_merge a b) v = true := by
  intro a b v h
  simp [gs_merge]
  induction b generalizing a with
  | nil => simp [List.foldl]; exact h
  | cons x xs ih =>
    simp [List.foldl]
    apply ih
    exact DELTA_003_07_gs_add_preserves a x v h

/-- DELTA_003_09_gs_add_idempotent (matches Coq) -/
theorem DELTA_003_09_gs_add_idempotent :
    ∀ (s : GSet) (v : Nat), gs_member s v = true → gs_add s v = s := by
  intro s v h
  unfold gs_add
  simp [gs_member] at h
  simp [h]

/-- DELTA_003_10_gc_empty_zero (matches Coq) -/
theorem DELTA_003_10_gc_empty_zero : gc_value [] = 0 := by
  rfl

-- ===============================================================================
-- PROOFS: CONSISTENT HASHING (5 theorems)
-- ===============================================================================

/-- DELTA_004_01_ring_add_increases (matches Coq) -/
theorem DELTA_004_01_ring_add_increases :
    ∀ (ring : HashRing) (pos : Nat) (node : NodeId),
    (ring_add_node ring pos node).ring_nodes.length = ring.ring_nodes.length + 1 := by
  intro ring pos node
  simp [ring_add_node]

/-- DELTA_004_02_ring_remove_decreases (matches Coq) -/
theorem DELTA_004_02_ring_remove_decreases :
    ∀ (ring : HashRing) (node : NodeId),
    (ring_remove_node ring node).ring_nodes.length ≤ ring.ring_nodes.length := by
  intro ring node
  simp [ring_remove_node]
  exact List.length_filter_le _ _

/-- DELTA_004_03_ring_size_preserved_add (matches Coq) -/
theorem DELTA_004_03_ring_size_preserved_add :
    ∀ (ring : HashRing) (pos : Nat) (node : NodeId),
    (ring_add_node ring pos node).ring_size = ring.ring_size := by
  intro _ _ _
  rfl

/-- DELTA_004_04_ring_size_preserved_remove (matches Coq) -/
theorem DELTA_004_04_ring_size_preserved_remove :
    ∀ (ring : HashRing) (node : NodeId),
    (ring_remove_node ring node).ring_size = ring.ring_size := by
  intro _ _
  rfl

/-- DELTA_004_05_empty_ring_no_lookup (matches Coq) -/
theorem DELTA_004_05_empty_ring_no_lookup :
    ∀ (key : Nat), ring_lookup { ring_nodes := [], ring_size := 0 } key = none := by
  intro _
  rfl

end RIINA.Domains.DELTA001_VerifiedDistribution
