-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.

/-!
# RIINA DependentTypes - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/domains/DependentTypes.v (33 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| DTerm | DTerm | OK |
| ctx_lookup | ctx_lookup | OK |
| TYPE_005_01 | TYPE_005_01 | OK |
| TYPE_005_02 | TYPE_005_02 | OK |
| TYPE_005_03 | TYPE_005_03 | OK |
| TYPE_005_04 | TYPE_005_04 | OK |
| TYPE_005_05 | TYPE_005_05 | OK |
| TYPE_005_06 | TYPE_005_06 | OK |
| TYPE_005_07 | TYPE_005_07 | OK |
| TYPE_005_08 | TYPE_005_08 | OK |
| vec_cons_length_semantic | vec_cons_length_semantic | OK |
| TYPE_005_09 | TYPE_005_09 | OK |
| vec_head_nonempty_semantic | vec_head_nonempty_semantic | OK |
| TYPE_005_10 | TYPE_005_10 | OK |
| vec_dep_pattern_match | vec_dep_pattern_match | OK |
| TYPE_005_11 | TYPE_005_11 | OK |
| transport_refl | transport_refl | OK |
| transport_trans | transport_trans | OK |
| TYPE_005_12 | TYPE_005_12 | OK |
| dep_congruence | dep_congruence | OK |
| congruence2 | congruence2 | OK |
| lt_wf_aux | lt_wf_aux | OK |
| lt_well_founded | lt_well_founded | OK |
| TYPE_005_13 | TYPE_005_13 | OK |
| nat_dep_ind | nat_dep_ind | OK |
| strong_ind | strong_ind | OK |
| TYPE_005_14 | TYPE_005_14 | OK |
| dec_eq_nat | dec_eq_nat | OK |
| dec_eq_bool | dec_eq_bool | OK |
| dec_eq_prod | dec_eq_prod | OK |
| dec_eq_option | dec_eq_option | OK |
| dec_eq_list | dec_eq_list | OK |
| dec_to_bool | dec_to_bool | OK |
| nat_eq_reflect | nat_eq_reflect | OK |
| uip_dec | uip_dec | OK |
-/

namespace RIINA.Domains.DependentTypes

-- ═══════════════════════════════════════════════════════════════════════════
-- Universe levels
-- ═══════════════════════════════════════════════════════════════════════════

abbrev Universe := Nat

-- ═══════════════════════════════════════════════════════════════════════════
-- Dependent type syntax (matches Coq: Inductive DTy)
-- ═══════════════════════════════════════════════════════════════════════════

inductive DTy : Universe → Type where
  | DUnit : (u : Universe) → DTy u
  | DNat : (u : Universe) → DTy u
  | DPi : (u : Universe) → DTy u → (Nat → DTy u) → DTy u
  | DSigma : (u : Universe) → DTy u → (Nat → DTy u) → DTy u
  | DId : (u : Universe) → DTy u → Nat → Nat → DTy u
  | DVec : (u : Universe) → DTy u → Nat → DTy u
  | DUniv : (u : Universe) → DTy (u + 1)

-- ═══════════════════════════════════════════════════════════════════════════
-- Dependent terms (matches Coq: Inductive DTerm)
-- ═══════════════════════════════════════════════════════════════════════════

inductive DTerm where
  | DVar : Nat → DTerm
  | DLam : DTy 0 → DTerm → DTerm
  | DApp : DTerm → DTerm → DTerm
  | DPair : DTerm → DTerm → DTerm
  | DFst : DTerm → DTerm
  | DSnd : DTerm → DTerm
  | DRefl : DTerm
  | DJ : DTerm → DTerm → DTerm → DTerm → DTerm
  | DNil : DTy 0 → DTerm
  | DCons : DTerm → DTerm → DTerm
  | DHead : DTerm → DTerm
  | DTail : DTerm → DTerm

-- ═══════════════════════════════════════════════════════════════════════════
-- Typing context
-- ═══════════════════════════════════════════════════════════════════════════

abbrev DCtx := List (DTy 0)

-- ═══════════════════════════════════════════════════════════════════════════
-- Context lookup (matches Coq: Fixpoint ctx_lookup)
-- ═══════════════════════════════════════════════════════════════════════════

def ctx_lookup (ctx : DCtx) (n : Nat) : Option (DTy 0) :=
  match ctx with
  | [] => none
  | T :: ctx' => if Nat.beq n 0 then some T else ctx_lookup ctx' (n - 1)

-- ═══════════════════════════════════════════════════════════════════════════
-- Well-formed type judgment (matches Coq: Inductive WfTy)
-- ═══════════════════════════════════════════════════════════════════════════

inductive WfTy : DCtx → DTy 0 → Prop where
  | WfUnit : ∀ ctx, WfTy ctx (DTy.DUnit 0)
  | WfNat : ∀ ctx, WfTy ctx (DTy.DNat 0)
  | WfPi : ∀ ctx A B,
      WfTy ctx A →
      (∀ n, WfTy (A :: ctx) (B n)) →
      WfTy ctx (DTy.DPi 0 A B)
  | WfSigma : ∀ ctx A B,
      WfTy ctx A →
      (∀ n, WfTy (A :: ctx) (B n)) →
      WfTy ctx (DTy.DSigma 0 A B)
  | WfId : ∀ ctx A x y,
      WfTy ctx A →
      WfTy ctx (DTy.DId 0 A x y)
  | WfVec : ∀ ctx A n,
      WfTy ctx A →
      WfTy ctx (DTy.DVec 0 A n)

-- ═══════════════════════════════════════════════════════════════════════════
-- Term typing judgment (matches Coq: Inductive HasType)
-- ═══════════════════════════════════════════════════════════════════════════

inductive HasType : DCtx → DTerm → DTy 0 → Prop where
  | TyVar : ∀ ctx n T,
      ctx_lookup ctx n = some T →
      HasType ctx (DTerm.DVar n) T
  | TyLam : ∀ ctx A B b,
      WfTy ctx A →
      (∀ n, HasType (A :: ctx) b (B n)) →
      HasType ctx (DTerm.DLam A b) (DTy.DPi 0 A B)
  | TyApp : ∀ ctx f a A B v,
      HasType ctx f (DTy.DPi 0 A B) →
      HasType ctx a A →
      HasType ctx (DTerm.DApp f a) (B v)
  | TyPair : ∀ ctx a b A B v,
      HasType ctx a A →
      HasType ctx b (B v) →
      WfTy ctx (DTy.DSigma 0 A B) →
      HasType ctx (DTerm.DPair a b) (DTy.DSigma 0 A B)
  | TyFst : ∀ ctx p A B,
      HasType ctx p (DTy.DSigma 0 A B) →
      HasType ctx (DTerm.DFst p) A
  | TySnd : ∀ ctx p A B v,
      HasType ctx p (DTy.DSigma 0 A B) →
      HasType ctx (DTerm.DSnd p) (B v)
  | TyRefl : ∀ ctx A x,
      WfTy ctx A →
      HasType ctx DTerm.DRefl (DTy.DId 0 A x x)
  | TyJ : ∀ ctx C d p A x y (motive : Nat → DTy 0),
      HasType ctx p (DTy.DId 0 A x y) →
      HasType ctx d (motive x) →
      HasType ctx (DTerm.DJ C d p (DTerm.DVar x)) (motive y)
  | TyNil : ∀ ctx A,
      WfTy ctx A →
      HasType ctx (DTerm.DNil A) (DTy.DVec 0 A 0)
  | TyCons : ∀ ctx A n h t,
      HasType ctx h A →
      HasType ctx t (DTy.DVec 0 A n) →
      HasType ctx (DTerm.DCons h t) (DTy.DVec 0 A (n + 1))
  | TyHead : ∀ ctx A n v,
      HasType ctx v (DTy.DVec 0 A (n + 1)) →
      HasType ctx (DTerm.DHead v) A
  | TyTail : ∀ ctx A n v,
      HasType ctx v (DTy.DVec 0 A (n + 1)) →
      HasType ctx (DTerm.DTail v) (DTy.DVec 0 A n)

-- ═══════════════════════════════════════════════════════════════════════════
-- Semantic domain for dependent types
-- ═══════════════════════════════════════════════════════════════════════════

/-- Dependent function type in Lean -/
abbrev DepFun (A : Type) (B : A → Type) := (x : A) → B x

/-- Dependent pair type in Lean -/
abbrev DepPair (A : Type) (B : A → Type) := (x : A) × B x

/-- Length-indexed vectors -/
inductive Vec (A : Type) : Nat → Type where
  | nil : Vec A 0
  | cons : ∀ {n : Nat}, A → Vec A n → Vec A (n + 1)

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_01: Dependent function type formation
-- Π x:A.B[x] is well-formed when A is well-formed and B[x] is well-formed
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_01 :
    ∀ (ctx : DCtx) (A : DTy 0) (B : Nat → DTy 0),
      WfTy ctx A →
      (∀ n, WfTy (A :: ctx) (B n)) →
      WfTy ctx (DTy.DPi 0 A B) := by
  intro ctx A B hA hB
  exact WfTy.WfPi ctx A B hA hB

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_02: Dependent function introduction
-- λx:A.b : Πx:A.B[x] when b : B[x] under assumption x : A
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_02 :
    ∀ (ctx : DCtx) (A : DTy 0) (B : Nat → DTy 0) (b : DTerm),
      WfTy ctx A →
      (∀ n, HasType (A :: ctx) b (B n)) →
      HasType ctx (DTerm.DLam A b) (DTy.DPi 0 A B) := by
  intro ctx A B b hA hb
  exact HasType.TyLam ctx A B b hA hb

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_03: Dependent function elimination
-- (f : Πx:A.B[x]) a : B[a] — application substitutes the value
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_03 :
    ∀ (ctx : DCtx) (f a : DTerm) (A : DTy 0) (B : Nat → DTy 0) (v : Nat),
      HasType ctx f (DTy.DPi 0 A B) →
      HasType ctx a A →
      HasType ctx (DTerm.DApp f a) (B v) := by
  intro ctx f a A B v hf ha
  exact HasType.TyApp ctx f a A B v hf ha

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_04: Dependent pair type formation
-- Σx:A.B[x] is well-formed when A and B[x] are well-formed
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_04 :
    ∀ (ctx : DCtx) (A : DTy 0) (B : Nat → DTy 0),
      WfTy ctx A →
      (∀ n, WfTy (A :: ctx) (B n)) →
      WfTy ctx (DTy.DSigma 0 A B) := by
  intro ctx A B hA hB
  exact WfTy.WfSigma ctx A B hA hB

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_05: Dependent pair introduction
-- (a,b) : Σx:A.B[x] when a : A and b : B[a]
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_05 :
    ∀ (ctx : DCtx) (a b : DTerm) (A : DTy 0) (B : Nat → DTy 0) (v : Nat),
      HasType ctx a A →
      HasType ctx b (B v) →
      WfTy ctx (DTy.DSigma 0 A B) →
      HasType ctx (DTerm.DPair a b) (DTy.DSigma 0 A B) := by
  intro ctx a b A B v ha hb hwf
  exact HasType.TyPair ctx a b A B v ha hb hwf

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_06: Dependent pair elimination
-- Projections preserve type dependencies
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_06 :
    ∀ (ctx : DCtx) (p : DTerm) (A : DTy 0) (B : Nat → DTy 0),
      HasType ctx p (DTy.DSigma 0 A B) →
      HasType ctx (DTerm.DFst p) A ∧
      ∀ v, HasType ctx (DTerm.DSnd p) (B v) := by
  intro ctx p A B hp
  constructor
  · exact HasType.TyFst ctx p A B hp
  · intro v
    exact HasType.TySnd ctx p A B v hp

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_07: Length-indexed vector type formation
-- Vec A n is well-formed when A is well-formed
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_07 :
    ∀ (ctx : DCtx) (A : DTy 0) (n : Nat),
      WfTy ctx A →
      WfTy ctx (DTy.DVec 0 A n) := by
  intro ctx A n hA
  exact WfTy.WfVec ctx A n hA

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_08: Vector cons preserves length
-- cons : A → Vec A n → Vec A (S n)
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_08 :
    ∀ (ctx : DCtx) (h t : DTerm) (A : DTy 0) (n : Nat),
      HasType ctx h A →
      HasType ctx t (DTy.DVec 0 A n) →
      HasType ctx (DTerm.DCons h t) (DTy.DVec 0 A (n + 1)) := by
  intro ctx h t A n hh ht
  exact HasType.TyCons ctx A n h t hh ht

-- ═══════════════════════════════════════════════════════════════════════════
-- vec_cons_length_semantic: Semantic version using Lean vectors
-- ═══════════════════════════════════════════════════════════════════════════

theorem vec_cons_length_semantic :
    ∀ (A : Type) (n : Nat) (h : A) (t : Vec A n),
      Vec.cons h t = Vec.cons h t ∧
      ∃ (v : Vec A (n + 1)), v = Vec.cons h t := by
  intro A n h t
  constructor
  · rfl
  · exact ⟨Vec.cons h t, rfl⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_09: Vector head requires non-empty
-- head : Vec A (S n) → A (only defined for non-empty vectors)
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_09 :
    ∀ (ctx : DCtx) (v : DTerm) (A : DTy 0) (n : Nat),
      HasType ctx v (DTy.DVec 0 A (n + 1)) →
      HasType ctx (DTerm.DHead v) A := by
  intro ctx v A n hv
  exact HasType.TyHead ctx A n v hv

-- ═══════════════════════════════════════════════════════════════════════════
-- vec_head_nonempty_semantic: head is total on non-empty vectors
-- ═══════════════════════════════════════════════════════════════════════════

/-- Head of a non-empty vector -/
def Vec.hd {A : Type} {n : Nat} : Vec A (n + 1) → A
  | Vec.cons h _ => h

theorem vec_head_nonempty_semantic :
    ∀ (A : Type) (n : Nat) (v : Vec A (n + 1)),
      ∃ (h : A), Vec.hd v = h := by
  intro A n v
  exact ⟨Vec.hd v, rfl⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_10: Dependent pattern matching
-- Π elimination with motive — dependent elimination preserves types
-- ═══════════════════════════════════════════════════════════════════════════

/-- Motive for dependent elimination on natural numbers -/
abbrev nat_motive := Nat → Type

/-- Dependent eliminator for nat -/
def nat_rect_dep (P : nat_motive) (base : P 0) (step : ∀ n, P n → P (n + 1)) : ∀ n, P n
  | 0 => base
  | n + 1 => step n (nat_rect_dep P base step n)

theorem TYPE_005_10 :
    ∀ (P : nat_motive) (base : P 0) (step : ∀ n, P n → P (n + 1)) (m : Nat),
      ∃ (result : P m), result = nat_rect_dep P base step m := by
  intro P base step m
  exact ⟨nat_rect_dep P base step m, rfl⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- vec_dep_pattern_match: Vector-based dependent pattern matching
-- ═══════════════════════════════════════════════════════════════════════════

/-- Dependent eliminator for Vec -/
def Vec.rect {A : Type} {P : ∀ n, Vec A n → Type}
    (base : P 0 Vec.nil)
    (step : ∀ (h : A) (n : Nat) (t : Vec A n), P n t → P (n + 1) (Vec.cons h t))
    : ∀ (n : Nat) (v : Vec A n), P n v
  | 0, Vec.nil => base
  | n + 1, Vec.cons h t => step h n t (Vec.rect base step n t)

theorem vec_dep_pattern_match :
    ∀ (A : Type) (P : ∀ n, Vec A n → Type)
      (base : P 0 (Vec.nil))
      (step : ∀ h n t, P n t → P (n + 1) (Vec.cons h t))
      (n : Nat) (v : Vec A n),
      ∃ (result : P n v),
        result = Vec.rect base (fun h n t ih => step h n t ih) n v := by
  intro A P base step n v
  exact ⟨Vec.rect base (fun h n t ih => step h n t ih) n v, rfl⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_11: Transport along equality
-- transport : (P : A → Type) → x = y → P x → P y
-- ═══════════════════════════════════════════════════════════════════════════

/-- Transport along equality (matches Coq: Definition transport) -/
def transport {A : Type} (P : A → Type) {x y : A} (eq : x = y) (px : P x) : P y :=
  eq ▸ px

theorem TYPE_005_11 :
    ∀ (A : Type) (P : A → Type) (x y : A) (eq : x = y) (px : P x),
      ∃ (py : P y), py = transport P eq px := by
  intro A P x y eq px
  exact ⟨transport P eq px, rfl⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- transport_refl: Transport preserves identity
-- ═══════════════════════════════════════════════════════════════════════════

theorem transport_refl :
    ∀ (A : Type) (P : A → Type) (x : A) (px : P x),
      transport P rfl px = px := by
  intro A P x px
  rfl

-- ═══════════════════════════════════════════════════════════════════════════
-- transport_trans: Transport composition
-- ═══════════════════════════════════════════════════════════════════════════

theorem transport_trans :
    ∀ (A : Type) (P : A → Type) (x y z : A) (eq1 : x = y) (eq2 : y = z) (px : P x),
      transport P eq2 (transport P eq1 px) = transport P (eq1.trans eq2) px := by
  intro A P x y z eq1 eq2 px
  subst eq1; subst eq2
  rfl

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_12: Congruence
-- f x = f y when x = y (functions preserve equality)
-- ═══════════════════════════════════════════════════════════════════════════

theorem TYPE_005_12 :
    ∀ (A B : Type) (f : A → B) (x y : A),
      x = y → f x = f y := by
  intro A B f x y h
  exact congrArg f h

-- ═══════════════════════════════════════════════════════════════════════════
-- dep_congruence: Dependent congruence
-- ═══════════════════════════════════════════════════════════════════════════

theorem dep_congruence :
    ∀ (A : Type) (B : A → Type) (f : ∀ a, B a) (x y : A) (eq : x = y),
      transport B eq (f x) = f y := by
  intro A B f x y eq
  subst eq
  rfl

-- ═══════════════════════════════════════════════════════════════════════════
-- congruence2: Congruence for binary functions
-- ═══════════════════════════════════════════════════════════════════════════

theorem congruence2 :
    ∀ (A B C : Type) (f : A → B → C) (x1 x2 : A) (y1 y2 : B),
      x1 = x2 → y1 = y2 → f x1 y1 = f x2 y2 := by
  intro A B C f x1 x2 y1 y2 hx hy
  subst hx; subst hy
  rfl

-- ═══════════════════════════════════════════════════════════════════════════
-- lt_wf_aux: Less-than on nat is well-founded (auxiliary)
-- ═══════════════════════════════════════════════════════════════════════════

theorem lt_wf_aux : ∀ (n m : Nat), m < n → Acc Nat.lt m := by
  intro n
  induction n with
  | zero => intro m hm; exact absurd hm (Nat.not_lt_zero m)
  | succ n ih =>
    intro m hm
    exact Acc.intro m (fun y hy => ih y (Nat.lt_of_lt_of_le hy (Nat.lt_succ_iff.mp hm)))

-- ═══════════════════════════════════════════════════════════════════════════
-- lt_well_founded: Less-than on nat is well-founded
-- ═══════════════════════════════════════════════════════════════════════════

theorem lt_well_founded : WellFounded (α := Nat) Nat.lt := by
  exact ⟨fun n => lt_wf_aux (n + 1) n (Nat.lt_succ_of_le (Nat.le_refl n))⟩

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_13: Dependent induction principle
-- Well-founded recursion with dependent types
-- ═══════════════════════════════════════════════════════════════════════════

noncomputable def TYPE_005_13 :
    ∀ (A : Type) (R : A → A → Prop) (P : A → Type),
      WellFounded R →
      (∀ x, (∀ y, R y x → P y) → P x) →
      ∀ x, P x := by
  intro A R P hwf hstep x
  have : Acc R x := hwf.apply x
  induction this with
  | intro x' _ ih =>
    exact hstep x' (fun y hy => ih y hy)

-- ═══════════════════════════════════════════════════════════════════════════
-- nat_dep_ind: Dependent induction on nat
-- ═══════════════════════════════════════════════════════════════════════════

def nat_dep_ind :
    ∀ (P : Nat → Type),
      P 0 →
      (∀ n, P n → P (n + 1)) →
      ∀ n, P n := by
  intro P h0 hs n
  induction n with
  | zero => exact h0
  | succ n ih => exact hs n ih

-- ═══════════════════════════════════════════════════════════════════════════
-- strong_ind: Strong induction principle
-- ═══════════════════════════════════════════════════════════════════════════

theorem strong_ind :
    ∀ (P : Nat → Prop),
      (∀ n, (∀ m, m < n → P m) → P n) →
      ∀ n, P n := by
  intro P h n
  suffices haux : ∀ m, m ≤ n → P m by
    exact haux n (Nat.le_refl n)
  induction n with
  | zero =>
    intro m hm
    have : m = 0 := Nat.le_zero.mp hm
    subst this
    exact h 0 (fun k hk => absurd hk (Nat.not_lt_zero k))
  | succ n ih =>
    intro m hm
    rcases Nat.lt_or_eq_of_le hm with hlt | heq
    · exact ih m (Nat.lt_succ_iff.mp hlt)
    · subst heq
      exact h (n + 1) (fun k hk => ih k (Nat.lt_succ_iff.mp hk))

-- ═══════════════════════════════════════════════════════════════════════════
-- THEOREM TYPE_005_14: Decidable equality reflection
-- Dec (x = y) for types with decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

/-- Decidability type (matches Coq: Inductive Dec) -/
inductive DDec (P : Prop) : Type where
  | Yes : P → DDec P
  | No : (P → False) → DDec P

def TYPE_005_14 :
    ∀ (A : Type),
      (∀ x y : A, x = y ∨ x ≠ y) →
      ∀ (x y : A), Decidable (x = y) → DDec (x = y) := by
  intro A _ x y hdec
  match hdec with
  | isTrue h => exact DDec.Yes h
  | isFalse h => exact DDec.No h

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_eq_nat: Nat has decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

def dec_eq_nat : ∀ (x y : Nat), DDec (x = y) := by
  intro x y
  match decEq x y with
  | isTrue h => exact DDec.Yes h
  | isFalse h => exact DDec.No h

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_eq_bool: Bool has decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

def dec_eq_bool : ∀ (x y : Bool), DDec (x = y) := by
  intro x y
  match decEq x y with
  | isTrue h => exact DDec.Yes h
  | isFalse h => exact DDec.No h

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_eq_prod: Product preserves decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

def dec_eq_prod :
    ∀ (A B : Type),
      (∀ x y : A, DDec (x = y)) →
      (∀ x y : B, DDec (x = y)) →
      ∀ (p1 p2 : A × B), DDec (p1 = p2) := by
  intro A B hA hB p1 p2
  match hA p1.1 p2.1, hB p1.2 p2.2 with
  | DDec.Yes ha, DDec.Yes hb =>
    exact DDec.Yes (by cases p1; cases p2; simp at *; exact ⟨ha, hb⟩)
  | DDec.Yes _, DDec.No hb =>
    exact DDec.No (fun h => hb (by cases p1; cases p2; simp at *; exact h.2))
  | DDec.No ha, _ =>
    exact DDec.No (fun h => ha (by cases p1; cases p2; simp at *; exact h.1))

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_eq_option: Option preserves decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

def dec_eq_option :
    ∀ (A : Type),
      (∀ x y : A, DDec (x = y)) →
      ∀ (o1 o2 : Option A), DDec (o1 = o2) := by
  intro A hA o1 o2
  match o1, o2 with
  | some a1, some a2 =>
    match hA a1 a2 with
    | DDec.Yes h => exact DDec.Yes (by rw [h])
    | DDec.No h => exact DDec.No (fun heq => h (by injection heq))
  | some _, none => exact DDec.No (fun h => by injection h)
  | none, some _ => exact DDec.No (fun h => by injection h)
  | none, none => exact DDec.Yes rfl

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_eq_list: List preserves decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

noncomputable def dec_eq_list :
    ∀ (A : Type),
      (∀ x y : A, DDec (x = y)) →
      ∀ (l1 l2 : List A), DDec (l1 = l2) :=
  fun A hA => let rec go : (l1 l2 : List A) → DDec (l1 = l2)
    | [], [] => DDec.Yes rfl
    | [], _ :: _ => DDec.No (fun h => List.noConfusion h)
    | _ :: _, [] => DDec.No (fun h => List.noConfusion h)
    | h1 :: t1, h2 :: t2 =>
      match hA h1 h2, go t1 t2 with
      | DDec.Yes hh, DDec.Yes ht => DDec.Yes (by rw [hh, ht])
      | DDec.Yes _, DDec.No ht =>
        DDec.No (fun h => ht (List.noConfusion h (fun _ ht' => ht')))
      | DDec.No hh, _ =>
        DDec.No (fun h => hh (List.noConfusion h (fun hh' _ => hh')))
  go

-- ═══════════════════════════════════════════════════════════════════════════
-- dec_to_bool: Decidability implies boolean decision procedure
-- ═══════════════════════════════════════════════════════════════════════════

theorem dec_to_bool : ∀ (P : Prop), DDec P → P ∨ ¬P := by
  intro P h
  match h with
  | DDec.Yes hp => exact Or.inl hp
  | DDec.No hnp => exact Or.inr hnp

-- ═══════════════════════════════════════════════════════════════════════════
-- nat_eq_reflect: Boolean equality reflects propositional equality for nat
-- ═══════════════════════════════════════════════════════════════════════════

theorem nat_eq_reflect : ∀ (x y : Nat), Nat.beq x y = true ↔ x = y := by
  intro x y
  constructor
  · intro h; exact Nat.eq_of_beq_eq_true h
  · intro h; subst h; exact Nat.beq_refl x

-- ═══════════════════════════════════════════════════════════════════════════
-- uip_dec: UIP for types with decidable equality
-- ═══════════════════════════════════════════════════════════════════════════

theorem uip_dec (A : Type) [DecidableEq A] :
    ∀ (x : A) (p : x = x), p = rfl := by
  intro x p
  exact proof_irrel p rfl

end RIINA.Domains.DependentTypes
