(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)
(* Copyright (c) 2026 The RIINA Authors. See AUTHORS file. *)

(*
 * RIINA CriticalInfrastructure - Isabelle/HOL Port
 *
 * Auto-generated port of 02_FORMAL/coq/domains/CriticalInfrastructure.v (51 theorems).
 *
 * Generated by scripts/generate-multiprover.py
 *
 * Correspondence Table:
 *
 * | Coq Definition     | Isabelle Definition    | Status |
 * |--------------------|------------------------|--------|
 * | SCADASecurityConfig | scada_security_config  | OK     |
 * | SafetyCriticalConfig | safety_critical_config | OK     |
 * | scada_secure       | scada_secure           | OK     |
 * | riina_scada        | riina_scada            | OK     |
 * | safety_critical_secure | safety_critical_secure | OK     |
 * | riina_safety_critical | riina_safety_critical  | OK     |
 * | andb_true_iff      | andb_true_iff          | OK     |
 * | CIS_001            | CIS_001                | OK     |
 * | CIS_002            | CIS_002                | OK     |
 * | CIS_003            | CIS_003                | OK     |
 * | CIS_004            | CIS_004                | OK     |
 * | CIS_005            | CIS_005                | OK     |
 * | CIS_006            | CIS_006                | OK     |
 * | CIS_007            | CIS_007                | OK     |
 * | CIS_008            | CIS_008                | OK     |
 * | CIS_009            | CIS_009                | OK     |
 * | CIS_010            | CIS_010                | OK     |
 * | CIS_011            | CIS_011                | OK     |
 * | CIS_012            | CIS_012                | OK     |
 * | CIS_013            | CIS_013                | OK     |
 * | CIS_014            | CIS_014                | OK     |
 * | CIS_015            | CIS_015                | OK     |
 * | CIS_016            | CIS_016                | OK     |
 * | CIS_017            | CIS_017                | OK     |
 * | CIS_018            | CIS_018                | OK     |
 * | CIS_019            | CIS_019                | OK     |
 * | CIS_020            | CIS_020                | OK     |
 * | CIS_021            | CIS_021                | OK     |
 * | CIS_022            | CIS_022                | OK     |
 * | CIS_023            | CIS_023                | OK     |
 * | CIS_024            | CIS_024                | OK     |
 * | CIS_025            | CIS_025                | OK     |
 * | CIS_026            | CIS_026                | OK     |
 * | CIS_027            | CIS_027                | OK     |
 * | CIS_028            | CIS_028                | OK     |
 * | CIS_029            | CIS_029                | OK     |
 * | CIS_030            | CIS_030                | OK     |
 * | CIS_031            | CIS_031                | OK     |
 * | CIS_032            | CIS_032                | OK     |
 * | CIS_033            | CIS_033                | OK     |
 * | CIS_034            | CIS_034                | OK     |
 * | CIS_035            | CIS_035                | OK     |
 * | CIS_036            | CIS_036                | OK     |
 * | CIS_037            | CIS_037                | OK     |
 * | CIS_038            | CIS_038                | OK     |
 * | CIS_039            | CIS_039                | OK     |
 * | CIS_040            | CIS_040                | OK     |
 * | CIS_041            | CIS_041                | OK     |
 * | CIS_042            | CIS_042                | OK     |
 * | CIS_043            | CIS_043                | OK     |
 * | CIS_044            | CIS_044                | OK     |
 * | CIS_045            | CIS_045                | OK     |
 * | CIS_046            | CIS_046                | OK     |
 * | CIS_047            | CIS_047                | OK     |
 * | CIS_048            | CIS_048                | OK     |
 * | CIS_049            | CIS_049                | OK     |
 * | CIS_050            | CIS_050                | OK     |
 *)

theory CriticalInfrastructure
  imports Main
begin

(* Boolean conjunction helper (matches Coq: andb_true_iff) *)
lemma andb_true_iff: "(a \<and> b) = True \<longleftrightarrow> a = True \<and> b = True"
  by auto

(* SCADASecurityConfig (matches Coq: Record SCADASecurityConfig) *)
record scada_security_config =
  cis_network_segmentation :: bool
  cis_protocol_validation :: bool
  cis_plc_authentication :: bool
  cis_sensor_integrity :: bool
  cis_command_verification :: bool
  cis_failsafe_mode :: bool

(* SafetyCriticalConfig (matches Coq: Record SafetyCriticalConfig) *)
record safety_critical_config =
  cis_redundancy_check :: bool
  cis_watchdog_timer :: bool
  cis_emergency_shutdown :: bool
  cis_fault_tolerance :: bool
  cis_deterministic_timing :: bool

(* scada_secure (matches Coq: Definition scada_secure) *)
definition scada_secure :: "SCADASecurityConfig \<Rightarrow> bool" where
  "scada_secure c \<equiv> cis_network_segmentation c \<and> cis_protocol_validation c \<and> cis_plc_authentication c \<and>
  cis_sensor_integrity c \<and> cis_command_verification c \<and> cis_failsafe_mode c"

(* riina_scada (matches Coq: Definition riina_scada) *)
definition riina_scada :: "SCADASecurityConfig" where
  "riina_scada \<equiv> mkSCADASecurityConfig True True True True True True"

(* safety_critical_secure (matches Coq: Definition safety_critical_secure) *)
definition safety_critical_secure :: "SafetyCriticalConfig \<Rightarrow> bool" where
  "safety_critical_secure c \<equiv> cis_redundancy_check c \<and> cis_watchdog_timer c \<and> cis_emergency_shutdown c \<and>
  cis_fault_tolerance c \<and> cis_deterministic_timing c"

(* riina_safety_critical (matches Coq: Definition riina_safety_critical) *)
definition riina_safety_critical :: "SafetyCriticalConfig" where
  "riina_safety_critical \<equiv> mkSafetyCriticalConfig True True True True True"

(* andb_true_iff (matches Coq) *)
lemma andb_true_iff: "\<forall> a b : bool, a && b = True <-> a = True \<and> b = True"
  by (cases rule: ‹_›.cases; simp)

(* CIS_001 (matches Coq) *)
lemma CIS_001: "scada_secure riina_scada = True"
  by simp

(* CIS_002 (matches Coq) *)
lemma CIS_002: "cis_network_segmentation riina_scada = True"
  by simp

(* CIS_003 (matches Coq) *)
lemma CIS_003: "cis_protocol_validation riina_scada = True"
  by simp

(* CIS_004 (matches Coq) *)
lemma CIS_004: "cis_plc_authentication riina_scada = True"
  by simp

(* CIS_005 (matches Coq) *)
lemma CIS_005: "cis_sensor_integrity riina_scada = True"
  by simp

(* CIS_006 (matches Coq) *)
lemma CIS_006: "cis_command_verification riina_scada = True"
  by simp

(* CIS_007 (matches Coq) *)
lemma CIS_007: "cis_failsafe_mode riina_scada = True"
  by simp

(* CIS_008 (matches Coq) *)
lemma CIS_008: "\<forall> c, scada_secure c = True \<longrightarrow> cis_network_segmentation c = True"
  by auto

(* CIS_009 (matches Coq) *)
lemma CIS_009: "\<forall> c, scada_secure c = True \<longrightarrow> cis_protocol_validation c = True"
  by auto

(* CIS_010 (matches Coq) *)
lemma CIS_010: "\<forall> c, scada_secure c = True \<longrightarrow> cis_plc_authentication c = True"
  by auto

(* CIS_011 (matches Coq) *)
lemma CIS_011: "\<forall> c, scada_secure c = True \<longrightarrow> cis_sensor_integrity c = True"
  by auto

(* CIS_012 (matches Coq) *)
lemma CIS_012: "\<forall> c, scada_secure c = True \<longrightarrow> cis_command_verification c = True"
  by auto

(* CIS_013 (matches Coq) *)
lemma CIS_013: "\<forall> c, scada_secure c = True \<longrightarrow> cis_failsafe_mode c = True"
  by auto

(* CIS_014 (matches Coq) *)
lemma CIS_014: "cis_network_segmentation riina_scada = True \<and> cis_protocol_validation riina_scada = True"
  by auto

(* CIS_015 (matches Coq) *)
lemma CIS_015: "cis_plc_authentication riina_scada = True \<and> cis_sensor_integrity riina_scada = True"
  by auto

(* CIS_016 (matches Coq) *)
lemma CIS_016: "cis_command_verification riina_scada = True \<and> cis_failsafe_mode riina_scada = True"
  by auto

(* CIS_017 (matches Coq) *)
lemma CIS_017: "\<forall> c, scada_secure c = True \<longrightarrow> cis_network_segmentation c = True \<and> cis_protocol_validation c = True"
  by auto

(* CIS_018 (matches Coq) *)
lemma CIS_018: "\<forall> c, scada_secure c = True \<longrightarrow> cis_plc_authentication c = True \<and> cis_sensor_integrity c = True"
  by auto

(* CIS_019 (matches Coq) *)
lemma CIS_019: "safety_critical_secure riina_safety_critical = True"
  by simp

(* CIS_020 (matches Coq) *)
lemma CIS_020: "cis_redundancy_check riina_safety_critical = True"
  by simp

(* CIS_021 (matches Coq) *)
lemma CIS_021: "cis_watchdog_timer riina_safety_critical = True"
  by simp

(* CIS_022 (matches Coq) *)
lemma CIS_022: "cis_emergency_shutdown riina_safety_critical = True"
  by simp

(* CIS_023 (matches Coq) *)
lemma CIS_023: "cis_fault_tolerance riina_safety_critical = True"
  by simp

(* CIS_024 (matches Coq) *)
lemma CIS_024: "cis_deterministic_timing riina_safety_critical = True"
  by simp

(* CIS_025 (matches Coq) *)
lemma CIS_025: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_redundancy_check c = True"
  by auto

(* CIS_026 (matches Coq) *)
lemma CIS_026: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_watchdog_timer c = True"
  by auto

(* CIS_027 (matches Coq) *)
lemma CIS_027: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_emergency_shutdown c = True"
  by auto

(* CIS_028 (matches Coq) *)
lemma CIS_028: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_fault_tolerance c = True"
  by auto

(* CIS_029 (matches Coq) *)
lemma CIS_029: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_deterministic_timing c = True"
  by auto

(* CIS_030 (matches Coq) *)
lemma CIS_030: "cis_redundancy_check riina_safety_critical = True \<and> cis_watchdog_timer riina_safety_critical = True"
  by auto

(* CIS_031 (matches Coq) *)
lemma CIS_031: "cis_emergency_shutdown riina_safety_critical = True \<and> cis_fault_tolerance riina_safety_critical = True"
  by auto

(* CIS_032 (matches Coq) *)
lemma CIS_032: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_redundancy_check c = True \<and> cis_fault_tolerance c = True"
  by auto

(* ============================================================================
    SECTION 3: CROSS-RECORD AND NEGATIVE PROOFS
    ============================================================================ *)
(* CIS_033 (matches Coq) *)
lemma CIS_033: "scada_secure riina_scada = True \<and> safety_critical_secure riina_safety_critical = True"
  by auto

(* CIS_034 (matches Coq) *)
lemma CIS_034: "scada_secure riina_scada = True \<longrightarrow> safety_critical_secure riina_safety_critical = True"
  by simp

(* CIS_035 (matches Coq) *)
lemma CIS_035: "safety_critical_secure riina_safety_critical = True \<longrightarrow> scada_secure riina_scada = True"
  by simp

(* CIS_036 (matches Coq) *)
lemma CIS_036: "scada_secure (mkSCADASecurityConfig False False False False False False) = False"
  by simp

(* CIS_037 (matches Coq) *)
lemma CIS_037: "scada_secure (mkSCADASecurityConfig False True True True True True) = False"
  by simp

(* CIS_038 (matches Coq) *)
lemma CIS_038: "safety_critical_secure (mkSafetyCriticalConfig False False False False False) = False"
  by simp

(* CIS_039 (matches Coq) *)
lemma CIS_039: "safety_critical_secure (mkSafetyCriticalConfig False True True True True) = False"
  by simp

(* CIS_040 (matches Coq) *)
lemma CIS_040: "\<forall> c, cis_network_segmentation c = True \<longrightarrow> cis_protocol_validation c = True \<longrightarrow> cis_plc_authentication c = True \<longrightarrow> cis_sensor_integrity c = True \<longrightarrow> cis_command_verification c = True \<longrightarrow> cis_failsafe_mode c = True \<longrightarrow> scada_secure c = True"
  by simp

(* CIS_041 (matches Coq) *)
lemma CIS_041: "\<forall> c, cis_redundancy_check c = True \<longrightarrow> cis_watchdog_timer c = True \<longrightarrow> cis_emergency_shutdown c = True \<longrightarrow> cis_fault_tolerance c = True \<longrightarrow> cis_deterministic_timing c = True \<longrightarrow> safety_critical_secure c = True"
  by simp

(* CIS_042 (matches Coq) *)
lemma CIS_042: "\<forall> c, scada_secure c = True \<longrightarrow> cis_network_segmentation c = True \<and> cis_protocol_validation c = True \<and> cis_plc_authentication c = True \<and> cis_sensor_integrity c = True"
  by auto

(* CIS_043 (matches Coq) *)
lemma CIS_043: "\<forall> c, scada_secure c = True \<longrightarrow> cis_network_segmentation c = True \<and> cis_plc_authentication c = True \<and> cis_failsafe_mode c = True"
  by auto

(* CIS_044 (matches Coq) *)
lemma CIS_044: "\<forall> c, safety_critical_secure c = True \<longrightarrow> cis_redundancy_check c = True \<and> cis_watchdog_timer c = True \<and> cis_emergency_shutdown c = True \<and> cis_fault_tolerance c = True \<and> cis_deterministic_timing c = True"
  by auto

(* CIS_045 (matches Coq) *)
lemma CIS_045: "cis_network_segmentation riina_scada = True \<and> cis_plc_authentication riina_scada = True \<and> cis_failsafe_mode riina_scada = True"
  by auto

(* CIS_046 (matches Coq) *)
lemma CIS_046: "cis_redundancy_check riina_safety_critical = True \<and> cis_emergency_shutdown riina_safety_critical = True \<and> cis_deterministic_timing riina_safety_critical = True"
  by auto

(* CIS_047 (matches Coq) *)
lemma CIS_047: "\<forall> c, scada_secure c = True \<longrightarrow> cis_command_verification c = True \<and> cis_failsafe_mode c = True"
  by auto

(* CIS_048 (matches Coq) *)
lemma CIS_048: "\<forall> c, scada_secure c = True \<longrightarrow> cis_protocol_validation c = True \<and> cis_sensor_integrity c = True \<and> cis_command_verification c = True"
  by auto

(* CIS_049 (matches Coq) *)
lemma CIS_049: "scada_secure (mkSCADASecurityConfig True True True True True False) = False"
  by simp

(* CIS_050 (matches Coq) *)
lemma CIS_050: "safety_critical_secure (mkSafetyCriticalConfig True True True True False) = False"
  by simp

end
