(* GENERATED-CORPUS-NOT-VERIFIED: machine-generated from the Coq sources by scripts/generate-full-stack.py. This file is NOT independently verified; its proof obligations are placeholders/stubs. Authoritative claim levels: website/public/metrics.json. Only the Coq lane is mechanized. *)
(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)
(* Copyright (c) 2026 The RIINA Authors. See AUTHORS file. *)

(*
 * RIINA ExecutionReceipts - Isabelle/HOL Port
 *
 * Auto-generated port of 02_FORMAL/coq/domains/ExecutionReceipts.v (56 theorems).
 *
 * Generated by scripts/generate-multiprover.py
 *
 * Correspondence Table:
 *
 * | Coq Definition     | Isabelle Definition    | Status |
 * |--------------------|------------------------|--------|
 * | ReceiptChain       | receipt_chain          | OK     |
 * | ReceiptConfig      | receipt_config         | OK     |
 * | DeterminismConfig  | determinism_config     | OK     |
 * | receipt_valid      | receipt_valid          | OK     |
 * | riina_receipt      | riina_receipt          | OK     |
 * | bad_receipt        | bad_receipt            | OK     |
 * | chain_valid        | chain_valid            | OK     |
 * | chain_length       | chain_length           | OK     |
 * | deterministic      | deterministic          | OK     |
 * | riina_determinism  | riina_determinism      | OK     |
 * | bad_determinism    | bad_determinism        | OK     |
 * | append_receipt     | append_receipt         | OK     |
 * | andb_true_iff      | andb_true_iff          | OK     |
 * | ER_001             | ER_001                 | OK     |
 * | ER_002             | ER_002                 | OK     |
 * | ER_003             | ER_003                 | OK     |
 * | ER_004             | ER_004                 | OK     |
 * | ER_005             | ER_005                 | OK     |
 * | ER_006             | ER_006                 | OK     |
 * | ER_007             | ER_007                 | OK     |
 * | ER_008             | ER_008                 | OK     |
 * | ER_009             | ER_009                 | OK     |
 * | ER_010             | ER_010                 | OK     |
 * | ER_011             | ER_011                 | OK     |
 * | ER_012             | ER_012                 | OK     |
 * | ER_013             | ER_013                 | OK     |
 * | ER_014             | ER_014                 | OK     |
 * | ER_015             | ER_015                 | OK     |
 * | ER_016             | ER_016                 | OK     |
 * | ER_017             | ER_017                 | OK     |
 * | ER_018             | ER_018                 | OK     |
 * | ER_019             | ER_019                 | OK     |
 * | ER_020             | ER_020                 | OK     |
 * | ER_021             | ER_021                 | OK     |
 * | ER_022             | ER_022                 | OK     |
 * | ER_023             | ER_023                 | OK     |
 * | ER_024             | ER_024                 | OK     |
 * | ER_025             | ER_025                 | OK     |
 * | ER_026             | ER_026                 | OK     |
 * | ER_027             | ER_027                 | OK     |
 * | ER_028             | ER_028                 | OK     |
 * | ER_029             | ER_029                 | OK     |
 * | ER_030             | ER_030                 | OK     |
 * | ER_031             | ER_031                 | OK     |
 * | ER_032             | ER_032                 | OK     |
 * | ER_033             | ER_033                 | OK     |
 * | ER_034             | ER_034                 | OK     |
 * | ER_035             | ER_035                 | OK     |
 * | ER_036             | ER_036                 | OK     |
 * | ER_037             | ER_037                 | OK     |
 * | ER_038             | ER_038                 | OK     |
 * | ER_039             | ER_039                 | OK     |
 * | ER_040             | ER_040                 | OK     |
 * | ER_041             | ER_041                 | OK     |
 * | ER_042             | ER_042                 | OK     |
 * | ER_043             | ER_043                 | OK     |
 * | ER_044             | ER_044                 | OK     |
 * | ER_045             | ER_045                 | OK     |
 * | ER_046             | ER_046                 | OK     |
 * | ER_047             | ER_047                 | OK     |
 * | ER_048             | ER_048                 | OK     |
 * | ER_049             | ER_049                 | OK     |
 * | ER_050             | ER_050                 | OK     |
 * | ER_051             | ER_051                 | OK     |
 * | ER_052             | ER_052                 | OK     |
 * | ER_053             | ER_053                 | OK     |
 * | ER_054             | ER_054                 | OK     |
 * | ER_055             | ER_055                 | OK     |
 *)

theory ExecutionReceipts
  imports Main
begin

(* Boolean conjunction helper (matches Coq: andb_true_iff) *)
lemma andb_true_iff: "(a \<and> b) = True \<longleftrightarrow> a = True \<and> b = True"
  by auto

(* ReceiptChain (matches Coq: Inductive ReceiptChain) *)
datatype receipt_chain =
    ChainEmpty
  |     ChainLink

(* ReceiptConfig (matches Coq: Record ReceiptConfig) *)
record receipt_config =
  er_hash_valid :: bool
  er_signature_valid :: bool
  er_timestamp_monotonic :: bool
  er_inputs_recorded :: bool
  er_outputs_recorded :: bool

(* DeterminismConfig (matches Coq: Record DeterminismConfig) *)
record determinism_config =
  er_same_input_same_output :: bool
  er_no_nondeterminism :: bool
  er_reproducible :: bool

(* receipt_valid (matches Coq: Definition receipt_valid) *)
definition receipt_valid :: "ReceiptConfig \<Rightarrow> bool" where
  "receipt_valid c \<equiv> er_hash_valid c \<and> er_signature_valid c \<and> er_timestamp_monotonic c \<and>
  er_inputs_recorded c \<and> er_outputs_recorded c"

(* riina_receipt (matches Coq: Definition riina_receipt) *)
definition riina_receipt :: "ReceiptConfig" where
  "riina_receipt \<equiv> mkReceiptConfig True True True True True"

(* bad_receipt (matches Coq: Definition bad_receipt) *)
definition bad_receipt :: "ReceiptConfig" where
  "bad_receipt \<equiv> mkReceiptConfig True False True True True"

(* chain_valid (matches Coq: Definition chain_valid) *)
fun chain_valid :: "ReceiptChain \<Rightarrow> bool" where
  "chain_valid ChainEmpty = true"

(* chain_length (matches Coq: Definition chain_length) *)
fun chain_length :: "ReceiptChain \<Rightarrow> nat" where
  "chain_length ChainEmpty = 0"

(* deterministic (matches Coq: Definition deterministic) *)
definition deterministic :: "DeterminismConfig \<Rightarrow> bool" where
  "deterministic c \<equiv> er_same_input_same_output c \<and> er_no_nondeterminism c \<and> er_reproducible c"

(* riina_determinism (matches Coq: Definition riina_determinism) *)
definition riina_determinism :: "DeterminismConfig" where
  "riina_determinism \<equiv> mkDeterminismConfig True True True"

(* bad_determinism (matches Coq: Definition bad_determinism) *)
definition bad_determinism :: "DeterminismConfig" where
  "bad_determinism \<equiv> mkDeterminismConfig True True False"

(* append_receipt (matches Coq: Definition append_receipt) *)
definition append_receipt :: "ReceiptChain \<Rightarrow> ReceiptChain" where
  "append_receipt c \<equiv> ChainLink rv phm c"

(* andb_true_iff (matches Coq) *)
lemma andb_true_iff: "\<forall> a b : bool, a && b = True <-> a = True \<and> b = True"
  by (cases rule: ‹_›.cases; simp)

(* ER_001 (matches Coq) *)
lemma ER_001: "receipt_valid riina_receipt = True"
  by simp

(* ER_002 (matches Coq) *)
lemma ER_002: "er_hash_valid riina_receipt = True"
  by simp

(* ER_003 (matches Coq) *)
lemma ER_003: "er_signature_valid riina_receipt = True"
  by simp

(* ER_004 (matches Coq) *)
lemma ER_004: "er_timestamp_monotonic riina_receipt = True"
  by simp

(* ER_005 (matches Coq) *)
lemma ER_005: "er_inputs_recorded riina_receipt = True"
  by simp

(* ER_006 (matches Coq) *)
lemma ER_006: "er_outputs_recorded riina_receipt = True"
  by simp

(* ER_007 (matches Coq) *)
lemma ER_007: "\<forall> c, receipt_valid c = True \<longrightarrow> er_hash_valid c = True"
  by auto

(* ER_008 (matches Coq) *)
lemma ER_008: "\<forall> c, receipt_valid c = True \<longrightarrow> er_signature_valid c = True"
  by auto

(* ER_009 (matches Coq) *)
lemma ER_009: "\<forall> c, receipt_valid c = True \<longrightarrow> er_timestamp_monotonic c = True"
  by auto

(* ER_010 (matches Coq) *)
lemma ER_010: "\<forall> c, receipt_valid c = True \<longrightarrow> er_inputs_recorded c = True"
  by auto

(* ER_011 (matches Coq) *)
lemma ER_011: "\<forall> c, receipt_valid c = True \<longrightarrow> er_outputs_recorded c = True"
  by auto

(* ER_012 (matches Coq) *)
lemma ER_012: "\<forall> c, receipt_valid c = True \<longrightarrow> er_hash_valid c = True \<and> er_signature_valid c = True"
  by auto

(* ER_013 (matches Coq) *)
lemma ER_013: "\<forall> c, receipt_valid c = True \<longrightarrow> er_inputs_recorded c = True \<and> er_outputs_recorded c = True"
  by auto

(* ER_014 (matches Coq) *)
lemma ER_014: "receipt_valid bad_receipt = False"
  by simp

(* ER_015 (matches Coq) *)
lemma ER_015: "\<forall> c, er_hash_valid c = True \<longrightarrow> er_signature_valid c = True \<longrightarrow> er_timestamp_monotonic c = True \<longrightarrow> er_inputs_recorded c = True \<longrightarrow> er_outputs_recorded c = True \<longrightarrow> receipt_valid c = True"
  by simp

(* ER_016 (matches Coq) *)
lemma ER_016: "\<forall> c, receipt_valid c = True \<longrightarrow> er_hash_valid c = True \<and> er_signature_valid c = True \<and> er_timestamp_monotonic c = True \<and> er_inputs_recorded c = True \<and> er_outputs_recorded c = True"
  by auto

(* ER_017 (matches Coq) *)
lemma ER_017: "chain_valid ChainEmpty = True"
  by simp

(* ER_018 (matches Coq) *)
lemma ER_018: "chain_valid (ChainLink True True ChainEmpty) = True"
  by simp

(* ER_019 (matches Coq) *)
lemma ER_019: "chain_valid (ChainLink True True (ChainLink True True ChainEmpty)) = True"
  by simp

(* ER_020 (matches Coq) *)
lemma ER_020: "chain_valid (ChainLink False True ChainEmpty) = False"
  by simp

(* ER_021 (matches Coq) *)
lemma ER_021: "chain_valid (ChainLink True False ChainEmpty) = False"
  by simp

(* ER_022 (matches Coq) *)
lemma ER_022: "chain_length ChainEmpty = 0"
  by simp

(* ER_023 (matches Coq) *)
lemma ER_023: "chain_length (ChainLink True True ChainEmpty) = 1"
  by simp

(* ER_024 (matches Coq) *)
lemma ER_024: "\<forall> rv phm rest, chain_length (ChainLink rv phm rest) = S (chain_length rest)"
  by simp

(* ER_025 (matches Coq) *)
lemma ER_025: "\<forall> rv phm rest, chain_valid (ChainLink rv phm rest) = True \<longrightarrow> rv = True"
  by auto

(* ER_026 (matches Coq) *)
lemma ER_026: "\<forall> rv phm rest, chain_valid (ChainLink rv phm rest) = True \<longrightarrow> phm = True"
  by auto

(* ER_027 (matches Coq) *)
lemma ER_027: "\<forall> rv phm rest, chain_valid (ChainLink rv phm rest) = True \<longrightarrow> chain_valid rest = True"
  by auto

(* ER_028 (matches Coq) *)
lemma ER_028: "\<forall> rv phm rest, chain_valid (ChainLink rv phm rest) = True \<longrightarrow> rv = True \<and> phm = True \<and> chain_valid rest = True"
  by auto

(* ER_029 (matches Coq) *)
lemma ER_029: "\<forall> rest, chain_valid rest = True \<longrightarrow> chain_valid (ChainLink True True rest) = True"
  by simp

(* ER_030 (matches Coq) *)
lemma ER_030: "\<forall> c, chain_length c \<ge> 0"
  by simp

(* ER_031 (matches Coq) *)
lemma ER_031: "\<forall> rv phm rest, chain_length (ChainLink rv phm rest) > 0"
  by simp

(* ER_032 (matches Coq) *)
lemma ER_032: "\<forall> rv phm rest, chain_length (ChainLink rv phm rest) \<ge> 1"
  by simp

(* ER_033 (matches Coq) *)
lemma ER_033: "\<forall> c, chain_valid c = True \<longrightarrow> chain_length c = 0 \<longrightarrow> c = ChainEmpty"
  by (cases rule: ‹_›.cases; simp)

(* ER_034 (matches Coq) *)
lemma ER_034: "chain_valid (ChainLink True True (ChainLink True True (ChainLink True True ChainEmpty))) = True"
  by simp

(* ER_035 (matches Coq) *)
lemma ER_035: "deterministic riina_determinism = True"
  by simp

(* ER_036 (matches Coq) *)
lemma ER_036: "er_same_input_same_output riina_determinism = True"
  by simp

(* ER_037 (matches Coq) *)
lemma ER_037: "er_no_nondeterminism riina_determinism = True"
  by simp

(* ER_038 (matches Coq) *)
lemma ER_038: "er_reproducible riina_determinism = True"
  by simp

(* ER_039 (matches Coq) *)
lemma ER_039: "\<forall> c, deterministic c = True \<longrightarrow> er_same_input_same_output c = True"
  by auto

(* ER_040 (matches Coq) *)
lemma ER_040: "\<forall> c, deterministic c = True \<longrightarrow> er_no_nondeterminism c = True"
  by auto

(* ER_041 (matches Coq) *)
lemma ER_041: "\<forall> c, deterministic c = True \<longrightarrow> er_reproducible c = True"
  by auto

(* ER_042 (matches Coq) *)
lemma ER_042: "\<forall> c, deterministic c = True \<longrightarrow> er_same_input_same_output c = True \<and> er_reproducible c = True"
  by auto

(* ER_043 (matches Coq) *)
lemma ER_043: "deterministic bad_determinism = False"
  by simp

(* ER_044 (matches Coq) *)
lemma ER_044: "\<forall> c, er_same_input_same_output c = True \<longrightarrow> er_no_nondeterminism c = True \<longrightarrow> er_reproducible c = True \<longrightarrow> deterministic c = True"
  by simp

(* ER_045 (matches Coq) *)
lemma ER_045: "\<forall> c rv phm, chain_length (append_receipt c rv phm) = S (chain_length c)"
  by simp

(* ER_046 (matches Coq) *)
lemma ER_046: "\<forall> c, chain_valid c = True \<longrightarrow> chain_valid (append_receipt c True True) = True"
  by simp

(* ER_047 (matches Coq) *)
lemma ER_047: "\<forall> c rv phm, chain_valid (append_receipt c rv phm) = True \<longrightarrow> chain_valid c = True"
  by auto

(* ER_048 (matches Coq) *)
lemma ER_048: "\<forall> c rv phm, chain_valid (append_receipt c rv phm) = True \<longrightarrow> rv = True"
  by auto

(* ER_049 (matches Coq) *)
lemma ER_049: "\<forall> c rv phm, chain_valid (append_receipt c rv phm) = True \<longrightarrow> phm = True"
  by auto

(* ER_050 (matches Coq) *)
lemma ER_050: "chain_length (append_receipt ChainEmpty True True) = 1"
  by simp

(* ER_051 (matches Coq) *)
lemma ER_051: "chain_valid (append_receipt ChainEmpty True True) = True"
  by simp

(* ER_052 (matches Coq) *)
lemma ER_052: "\<forall> c, chain_valid c = True \<longrightarrow> chain_length (append_receipt c True True) = S (chain_length c) \<and> chain_valid (append_receipt c True True) = True"
  by auto

(* ER_053 (matches Coq) *)
lemma ER_053: "\<forall> c rv phm, chain_valid (append_receipt c rv phm) = True \<longrightarrow> rv = True \<and> phm = True \<and> chain_valid c = True"
  by auto

(* ER_054 (matches Coq) *)
lemma ER_054: "\<forall> c1 c2 rv phm, chain_length c1 = chain_length c2 \<longrightarrow> chain_length (append_receipt c1 rv phm) = chain_length (append_receipt c2 rv phm)"
  by simp

(* ER_055 (matches Coq) *)
lemma ER_055: "receipt_valid riina_receipt = True \<and> deterministic riina_determinism = True \<and> chain_valid (ChainLink True True ChainEmpty) = True"
  by simp

end
