(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)
(* Copyright (c) 2026 The RIINA Authors. See AUTHORS file. *)

(*
 * RIINA ContextProperties - Isabelle/HOL Port
 *
 * Auto-generated port of 02_FORMAL/coq/properties/ContextProperties.v (43 theorems).
 *
 * Generated by scripts/generate-multiprover.py
 *
 * Correspondence Table:
 *
 * | Coq Definition     | Isabelle Definition    | Status |
 * |--------------------|------------------------|--------|
 * | free_in_dec        | free_in_dec            | OK     |
 * | lookup_cons_neq_inv | lookup_cons_neq_inv    | OK     |
 * | lookup_deterministic | lookup_deterministic   | OK     |
 * | lookup_cons_inv    | lookup_cons_inv        | OK     |
 * | lookup_weaken_neq  | lookup_weaken_neq      | OK     |
 * | typing_weaken_head | typing_weaken_head     | OK     |
 * | typing_weaken_fresh | typing_weaken_fresh    | OK     |
 * | typing_strengthen_head | typing_strengthen_head | OK     |
 * | typing_exchange    | typing_exchange        | OK     |
 * | typing_delta_irrelevance | typing_delta_irrelevance | OK     |
 * | typing_shadow      | typing_shadow          | OK     |
 * | closed_no_free_vars | closed_no_free_vars    | OK     |
 * | typing_weaken_closed | typing_weaken_closed   | OK     |
 * | typing_weaken_multi_closed | typing_weaken_multi_closed | OK     |
 * | typing_weaken_prefix | typing_weaken_prefix   | OK     |
 * | store_extends_refl | store_extends_refl     | OK     |
 * | store_extends_trans | store_extends_trans    | OK     |
 * | typing_weaken_store | typing_weaken_store    | OK     |
 * | typing_weaken_head_delta | typing_weaken_head_delta | OK     |
 * | typing_weaken_two  | typing_weaken_two      | OK     |
 * | typing_weaken_head_store | typing_weaken_head_store | OK     |
 * | lookup_app_l       | lookup_app_l           | OK     |
 * | lookup_app_r       | lookup_app_r           | OK     |
 * | lookup_nil         | lookup_nil             | OK     |
 * | lookup_head_eq     | lookup_head_eq         | OK     |
 * | typing_contract    | typing_contract        | OK     |
 * | store_wf_runtime_entry_typed | store_wf_runtime_entry_typed | OK     |
 * | store_wf_bidirectional | store_wf_bidirectional | OK     |
 * | subst_closed_typing | subst_closed_typing    | OK     |
 * | typing_weaken_fresh_list | typing_weaken_fresh_list | OK     |
 * | lookup_singleton   | lookup_singleton       | OK     |
 * | lookup_cons_tail   | lookup_cons_tail       | OK     |
 * | lookup_dec         | lookup_dec             | OK     |
 * | closed_typing_any_ctx | closed_typing_any_ctx  | OK     |
 * | typing_weaken_exchange | typing_weaken_exchange | OK     |
 * | typing_weaken_append | typing_weaken_append   | OK     |
 * | typing_prefix_sufficient | typing_prefix_sufficient | OK     |
 * | typing_singleton_var | typing_singleton_var   | OK     |
 * | nil_ctx_no_free_vars | nil_ctx_no_free_vars   | OK     |
 * | typing_weaken_cons_right | typing_weaken_cons_right | OK     |
 * | typing_weaken_singleton | typing_weaken_singleton | OK     |
 * | typing_weaken_double | typing_weaken_double   | OK     |
 * | nil_ctx_typed_closed | nil_ctx_typed_closed   | OK     |
 *)

theory ContextProperties
  imports Main
begin

(* Decidability of [free_in]: for any variable [x] and expression [e],
    we can decide whether [x] occurs free in [e]. This is essential for
    automation and case analysis in proofs about weakening/strengthening. *)
(* free_in_dec (matches Coq) *)
lemma free_in_dec: "\<forall>x e. (free_in x e) \<or> (~ free_in x e)"
  by auto

(* If lookup finds a binding through a non-matching head, the binding is in the tail. *)
(* lookup_cons_neq_inv (matches Coq) *)
lemma lookup_cons_neq_inv: "\<forall>x y U Γ T. lookup x ((y, U) :: Γ) = Some T \<longrightarrow> x \<noteq> y \<longrightarrow> lookup x Γ = Some T"
  by auto

(* Lookup is deterministic (functional). *)
(* lookup_deterministic (matches Coq) *)
lemma lookup_deterministic: "\<forall>x Γ T1 T2. lookup x Γ = Some T1 \<longrightarrow> lookup x Γ = Some T2 \<longrightarrow> T1 = T2"
  by simp

(* Lookup in an extended context: either the head matches or it's in the tail. *)
(* lookup_cons_inv (matches Coq) *)
lemma lookup_cons_inv: "\<forall>x y U Γ T. lookup x ((y, U) :: Γ) = Some T \<longrightarrow> (x = y \<and> T = U) \<or> (x \<noteq> y \<and> lookup x Γ = Some T)"
  by auto

(* Weakening lookup: if x is found in Γ and x ≠ y, x is still found after prepending (y,U). *)
(* lookup_weaken_neq (matches Coq) *)
lemma lookup_weaken_neq: "\<forall>x Γ T y U. lookup x Γ = Some T \<longrightarrow> x \<noteq> y \<longrightarrow> lookup x ((y, U) :: Γ) = Some T"
  by auto

(* Adding an unused binding to the head of Γ preserves typing.
    This is a direct corollary of [context_invariance] from Preservation.v. *)
(* typing_weaken_head (matches Coq) *)
lemma typing_weaken_head: "\<forall>Γ Σ Δ e T ε y U. has_type Γ Σ Δ e T ε \<longrightarrow> ~ free_in y e \<longrightarrow> has_type ((y, U) :: Γ) Σ Δ e T ε"
  by auto

(* Unconditional weakening when the new binding's name is fresh
    (not in the domain of Γ and not free in e).
    Convenience wrapper combining free_in_context with typing_weaken_head. *)
(* typing_weaken_fresh (matches Coq) *)
lemma typing_weaken_fresh: "\<forall>Γ Σ Δ e T ε y U. has_type Γ Σ Δ e T ε \<longrightarrow> lookup y Γ = None \<longrightarrow> has_type ((y, U) :: Γ) Σ Δ e T ε"
  by auto

(* Removing an unused head binding preserves typing.
    Dual of [typing_weaken_head]. *)
(* typing_strengthen_head (matches Coq) *)
lemma typing_strengthen_head: "\<forall>Γ Σ Δ e T ε y U. has_type ((y, U) :: Γ) Σ Δ e T ε \<longrightarrow> ~ free_in y e \<longrightarrow> has_type Γ Σ Δ e T ε"
  by auto

(* Swapping two non-conflicting adjacent bindings preserves typing. *)
(* typing_exchange (matches Coq) *)
lemma typing_exchange: "\<forall>Γ Σ Δ e T ε x Tx y Ty. has_type ((x, Tx) :: (y, Ty) :: Γ) Σ Δ e T ε \<longrightarrow> x \<noteq> y \<longrightarrow> has_type ((y, Ty) :: (x, Tx) :: Γ) Σ Δ e T ε"
  by auto

(* The security context Δ does not affect typing derivations.
    This is because no typing rule discriminates on the value of Δ;
    it is threaded uniformly through all rules. *)
(* typing_delta_irrelevance (matches Coq) *)
lemma typing_delta_irrelevance: "\<forall>Γ Σ Δ1 Δ2 e T ε. has_type Γ Σ Δ1 e T ε \<longrightarrow> has_type Γ Σ Δ2 e T ε"
  by auto

(* If a binding (x, T1) shadows an earlier (x, T2), the earlier is irrelevant. *)
(* typing_shadow (matches Coq) *)
lemma typing_shadow: "\<forall>Γ Σ Δ e T ε x T1 T2. has_type ((x, T1) :: (x, T2) :: Γ) Σ Δ e T ε \<longrightarrow> has_type ((x, T1) :: Γ) Σ Δ e T ε"
  by auto

(* A well-typed closed term has no free variables.
    This is a direct consequence of [free_in_context]. *)
(* closed_no_free_vars (matches Coq) *)
lemma closed_no_free_vars: "\<forall>Σ Δ e T ε x. has_type nil Σ Δ e T ε \<longrightarrow> ~ free_in x e"
  by auto

(* Closed terms can be typed in any type environment.
    This re-exports [closed_typing_weakening] under a more discoverable name. *)
(* typing_weaken_closed (matches Coq) *)
lemma typing_weaken_closed: "\<forall>Γ Σ Δ e T ε. has_type nil Σ Δ e T ε \<longrightarrow> has_type Γ Σ Δ e T ε"
  by auto

(* Weakening by an entire list of bindings, when the expression is closed. *)
(* typing_weaken_multi_closed (matches Coq) *)
lemma typing_weaken_multi_closed: "\<forall>Γ1 Γ2 Σ Δ e T ε. has_type nil Σ Δ e T ε \<longrightarrow> has_type (Γ1 ++ Γ2) Σ Δ e T ε"
  by auto

(* Weakening by prepending a list of bindings when none shadow free variables. *)
(* typing_weaken_prefix (matches Coq) *)
lemma typing_weaken_prefix: "\<forall>Γ1 Γ2 Σ Δ e T ε. has_type Γ2 Σ Δ e T ε \<longrightarrow> (\<forall>x. free_in x e \<longrightarrow> lookup x Γ2 = lookup x (Γ1 ++ Γ2)) \<longrightarrow> has_type (Γ1 ++ Γ2) Σ Δ e T ε"
  by auto

(* Store typing extension is reflexive.
    Re-exported from StrongNorm.v for discoverability. *)
(* store_extends_refl (matches Coq) *)
lemma store_extends_refl: "\<forall>Σ. store_ty_extends Σ Σ"
  by auto

(* Store typing extension is transitive.
    Re-exported from Typing.v for discoverability. *)
(* store_extends_trans (matches Coq) *)
lemma store_extends_trans: "\<forall>Σ1 Σ2 Σ3. store_ty_extends Σ1 Σ2 \<longrightarrow> store_ty_extends Σ2 Σ3 \<longrightarrow> store_ty_extends Σ1 Σ3"
  by auto

(* Store extension preserves well-typedness (lifts store_ty_extends_preserves_typing
    to a more discoverable name). *)
(* typing_weaken_store (matches Coq) *)
lemma typing_weaken_store: "\<forall>Γ Σ Σ' Δ e T ε. has_type Γ Σ Δ e T ε \<longrightarrow> store_ty_extends Σ Σ' \<longrightarrow> has_type Γ Σ' Δ e T ε"
  by auto

(* Weaken both context and security level simultaneously. *)
(* typing_weaken_head_delta (matches Coq) *)
lemma typing_weaken_head_delta: "\<forall>Γ Σ Δ1 Δ2 e T ε y U. has_type Γ Σ Δ1 e T ε \<longrightarrow> ~ free_in y e \<longrightarrow> has_type ((y, U) :: Γ) Σ Δ2 e T ε"
  by auto

(* Weakening after exchange: if we have typing in Γ and x ≠ y,
    we can add both bindings in either order. *)
(* typing_weaken_two (matches Coq) *)
lemma typing_weaken_two: "\<forall>Γ Σ Δ e T ε x Tx y Ty. has_type Γ Σ Δ e T ε \<longrightarrow> ~ free_in x e \<longrightarrow> ~ free_in y e \<longrightarrow> has_type ((x, Tx) :: (y, Ty) :: Γ) Σ Δ e T ε"
  by auto

(* Weakening + store extension simultaneously. *)
(* typing_weaken_head_store (matches Coq) *)
lemma typing_weaken_head_store: "\<forall>Γ Σ Σ' Δ e T ε y U. has_type Γ Σ Δ e T ε \<longrightarrow> ~ free_in y e \<longrightarrow> store_ty_extends Σ Σ' \<longrightarrow> has_type ((y, U) :: Γ) Σ' Δ e T ε"
  by auto

(* If x is found in the first context, it's found in the append. *)
(* lookup_app_l (matches Coq) *)
lemma lookup_app_l: "\<forall>x Γ1 Γ2 T. lookup x Γ1 = Some T \<longrightarrow> lookup x (Γ1 ++ Γ2) = Some T"
  by auto

(* If x is not in the first context, lookup in append depends on the tail. *)
(* lookup_app_r (matches Coq) *)
lemma lookup_app_r: "\<forall>x Γ1 Γ2. lookup x Γ1 = None \<longrightarrow> lookup x (Γ1 ++ Γ2) = lookup x Γ2"
  by auto

(* Lookup in nil is always None. *)
(* lookup_nil (matches Coq) *)
lemma lookup_nil: "\<forall>x. lookup x nil = None"
  by simp

(* If lookup succeeds in the head, x equals the head's name. *)
(* lookup_head_eq (matches Coq) *)
lemma lookup_head_eq: "\<forall>x T Γ. lookup x ((x, T) :: Γ) = Some T"
  by simp

(* Duplicate adjacent bindings can be contracted.
    (x,T)::(x,T)::Γ ≡ (x,T)::Γ *)
(* typing_contract (matches Coq) *)
lemma typing_contract: "\<forall>Γ Σ Δ e T ε x Tx. has_type ((x, Tx) :: (x, Tx) :: Γ) Σ Δ e T ε \<longrightarrow> has_type ((x, Tx) :: Γ) Σ Δ e T ε"
  by auto

(* If store is well-formed, every runtime value has a store typing entry. *)
(* store_wf_runtime_entry_typed (matches Coq) *)
lemma store_wf_runtime_entry_typed: "\<forall>Σ st l v. store_wf Σ st \<longrightarrow> store_lookup l st = Some v \<longrightarrow> \<exists>T sl. store_ty_lookup l Σ = Some (T, sl)"
  by auto

(* Store well-formedness implies typed and runtime stores agree on domain. *)
(* store_wf_bidirectional (matches Coq) *)
lemma store_wf_bidirectional: "\<forall>Σ st l. store_wf Σ st \<longrightarrow> (\<exists>T sl. store_ty_lookup l Σ = Some (T, sl)) <-> (\<exists>v. store_lookup l st = Some v)"
  by auto

(* Substitution into closed (well-typed in empty context) terms is the identity. *)
(* subst_closed_typing (matches Coq) *)
lemma subst_closed_typing: "\<forall>Σ Δ e T ε x v. has_type nil Σ Δ e T ε \<longrightarrow> subst x v e = e"
  by auto

(* Weakening by a list of fresh bindings preserves typing for open terms. *)
(* typing_weaken_fresh_list (matches Coq) *)
lemma typing_weaken_fresh_list: "\<forall>Γ1 Γ2 Σ Δ e T ε. has_type Γ2 Σ Δ e T ε \<longrightarrow> (\<forall>x. free_in x e \<longrightarrow> lookup x Γ1 = None) \<longrightarrow> has_type (Γ1 ++ Γ2) Σ Δ e T ε"
  by auto

(* Lookup in a singleton context. *)
(* lookup_singleton (matches Coq) *)
lemma lookup_singleton: "\<forall>x T. lookup x ((x, T) :: nil) = Some T"
  by simp

(* If lookup in (y,U)::Γ returns T and x ≠ y, then T comes from Γ.
    (Same as lookup_cons_inv above but with reordered args for ergonomics.) *)
(* lookup_cons_tail (matches Coq) *)
lemma lookup_cons_tail: "\<forall>x y U T Γ. x \<noteq> y \<longrightarrow> lookup x ((y, U) :: Γ) = Some T \<longrightarrow> lookup x Γ = Some T"
  by auto

(* Lookup is decidable. *)
(* lookup_dec (matches Coq) *)
lemma lookup_dec: "\<forall>x Γ. (\<exists>T. lookup x Γ = Some T) \<or> (lookup x Γ = None)"
  by simp

(* Closed terms are invariant under any context and security level change. *)
(* closed_typing_any_ctx (matches Coq) *)
lemma closed_typing_any_ctx: "\<forall>Γ Σ Δ1 Δ2 e T ε. has_type nil Σ Δ1 e T ε \<longrightarrow> has_type Γ Σ Δ2 e T ε"
  by auto

(* Weakening commutes with exchange: can weaken and exchange simultaneously. *)
(* typing_weaken_exchange (matches Coq) *)
lemma typing_weaken_exchange: "\<forall>Γ Σ Δ e T ε x Tx y Ty. has_type Γ Σ Δ e T ε \<longrightarrow> ~ free_in x e \<longrightarrow> ~ free_in y e \<longrightarrow> x \<noteq> y \<longrightarrow> has_type ((y, Ty) :: (x, Tx) :: Γ) Σ Δ e T ε"
  by auto

(* Weakening by appending: lookup agreement on free vars gives typing. *)
(* typing_weaken_append (matches Coq) *)
lemma typing_weaken_append: "\<forall>Γ1 Γ2 Σ Δ e T ε. has_type Γ1 Σ Δ e T ε \<longrightarrow> has_type (Γ1 ++ Γ2) Σ Δ e T ε"
  by auto

(* Removing a suffix from Γ preserves typing if all free variables
    are bound in the prefix. *)
(* typing_prefix_sufficient (matches Coq) *)
lemma typing_prefix_sufficient: "\<forall>Γ1 Γ2 Σ Δ e T ε. has_type (Γ1 ++ Γ2) Σ Δ e T ε \<longrightarrow> (\<forall>x. free_in x e \<longrightarrow> lookup x Γ1 = lookup x (Γ1 ++ Γ2)) \<longrightarrow> has_type Γ1 Σ Δ e T ε"
  by auto

(* Typing in singleton context: a variable is well-typed with pure effect. *)
(* typing_singleton_var (matches Coq) *)
lemma typing_singleton_var: "\<forall>x T Σ Δ. has_type ((x, T) :: nil) Σ Δ (EVar x) T EffectPure"
  by simp

(* Typing in empty context: free variables must not exist *)
(* nil_ctx_no_free_vars (matches Coq) *)
lemma nil_ctx_no_free_vars: "\<forall>Σ Δ e T ε x. has_type nil Σ Δ e T ε \<longrightarrow> ~ free_in x e"
  by auto

(* Weakening by cons on the right side *)
(* typing_weaken_cons_right (matches Coq) *)
lemma typing_weaken_cons_right: "\<forall>Γ Σ Δ e T ε y Ty. has_type Γ Σ Δ e T ε \<longrightarrow> has_type (Γ ++ (y, Ty) :: nil) Σ Δ e T ε"
  by auto

(* Singleton context extension *)
(* typing_weaken_singleton (matches Coq) *)
lemma typing_weaken_singleton: "\<forall>Σ Δ e T ε x Tx. has_type nil Σ Δ e T ε \<longrightarrow> has_type ((x, Tx) :: nil) Σ Δ e T ε"
  by auto

(* Double singleton context extension *)
(* typing_weaken_double (matches Coq) *)
lemma typing_weaken_double: "\<forall>Σ Δ e T ε x Tx y Ty. has_type nil Σ Δ e T ε \<longrightarrow> has_type ((x, Tx) :: (y, Ty) :: nil) Σ Δ e T ε"
  by auto

(* Typing in empty context is closed *)
(* nil_ctx_typed_closed (matches Coq) *)
lemma nil_ctx_typed_closed: "\<forall>Σ Δ e T ε. has_type nil Σ Δ e T ε \<longrightarrow> \<forall>x. ~ free_in x e"
  by auto

end
