(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)
(* Copyright (c) 2026 The RIINA Authors. See AUTHORS file. *)

(*
 * RIINA EffectSafety - Isabelle/HOL Port
 *
 * Auto-generated port of 02_FORMAL/coq/properties/EffectSafety.v (53 theorems).
 *
 * Generated by scripts/generate-multiprover.py
 *
 * Correspondence Table:
 *
 * | Coq Definition     | Isabelle Definition    | Status |
 * |--------------------|------------------------|--------|
 * | effect_join_pure_inv | effect_join_pure_inv   | OK     |
 * | effect_join_write_not_pure | effect_join_write_not_pure | OK     |
 * | effect_join_read_not_pure | effect_join_read_not_pure | OK     |
 * | value_dec          | value_dec              | OK     |
 * | pure_step_preserves_store | pure_step_preserves_store | OK     |
 * | pure_step_preserves_ctx | pure_step_preserves_ctx | OK     |
 * | preservation_pure  | preservation_pure      | OK     |
 * | pure_multi_step_preserves_store | pure_multi_step_preserves_store | OK     |
 * | multi_step_value_inv | multi_step_value_inv   | OK     |
 * | atomic_value_pure  | atomic_value_pure      | OK     |
 * | effect_level_zero_is_pure | effect_level_zero_is_pure | OK     |
 * | effect_join_nonpure | effect_join_nonpure    | OK     |
 * | effect_join_monotone | effect_join_monotone   | OK     |
 * | effect_join_mono_l | effect_join_mono_l     | OK     |
 * | effect_join_mono_r | effect_join_mono_r     | OK     |
 * | effect_leq_pure    | effect_leq_pure        | OK     |
 * | read_leq_write     | read_leq_write         | OK     |
 * | write_subsumes_read | write_subsumes_read    | OK     |
 * | write_leq_filesystem | write_leq_filesystem   | OK     |
 * | pure_leq_read      | pure_leq_read          | OK     |
 * | pure_leq_write     | pure_leq_write         | OK     |
 * | read_neq_write     | read_neq_write         | OK     |
 * | effect_join_pure_l | effect_join_pure_l     | OK     |
 * | effect_join_idem   | effect_join_idem       | OK     |
 * | base_value_always_pure | base_value_always_pure | OK     |
 * | pure_multi_step_preserves_ctx | pure_multi_step_preserves_ctx | OK     |
 * | effect_read_not_pure | effect_read_not_pure   | OK     |
 * | effect_write_not_pure | effect_write_not_pure  | OK     |
 * | effect_filesystem_not_pure | effect_filesystem_not_pure | OK     |
 * | effect_network_not_pure | effect_network_not_pure | OK     |
 * | effect_system_not_pure | effect_system_not_pure | OK     |
 * | effect_crypto_not_pure | effect_crypto_not_pure | OK     |
 * | effect_random_not_pure | effect_random_not_pure | OK     |
 * | effect_time_not_pure | effect_time_not_pure   | OK     |
 * | effect_process_not_pure | effect_process_not_pure | OK     |
 * | effect_netsecure_not_pure | effect_netsecure_not_pure | OK     |
 * | effect_level_pure  | effect_level_pure      | OK     |
 * | effect_level_read  | effect_level_read      | OK     |
 * | effect_level_write | effect_level_write     | OK     |
 * | effect_level_pure_min | effect_level_pure_min  | OK     |
 * | pure_multi_step_compose | pure_multi_step_compose | OK     |
 * | pure_leq_filesystem | pure_leq_filesystem    | OK     |
 * | read_leq_filesystem | read_leq_filesystem    | OK     |
 * | pure_leq_network   | pure_leq_network       | OK     |
 * | pure_leq_crypto    | pure_leq_crypto        | OK     |
 * | effect_join_pure_pure | effect_join_pure_pure  | OK     |
 * | pure_lt_read       | pure_lt_read           | OK     |
 * | read_lt_write      | read_lt_write          | OK     |
 * | effect_leq_join_l  | effect_leq_join_l      | OK     |
 * | effect_leq_join_r  | effect_leq_join_r      | OK     |
 * | effect_join_network_not_pure | effect_join_network_not_pure | OK     |
 * | effect_level_positive_not_pure | effect_level_positive_not_pure | OK     |
 * | effect_join_pure_r | effect_join_pure_r     | OK     |
 *)

theory EffectSafety
  imports Main
begin

(* If the join of two effects is EffPure, both must be EffPure.
    This is because EffPure has level 0 (the minimum), and effect_join
    takes the maximum. *)
(* effect_join_pure_inv (matches Coq) *)
lemma effect_join_pure_inv: "\<forall> ε1 ε2, effect_join ε1 ε2 = EffPure \<longrightarrow> ε1 = EffPure \<and> ε2 = EffPure"
  by (cases rule: ‹_›.cases; simp)

(* Join with EffWrite is never pure. *)
(* effect_join_write_not_pure (matches Coq) *)
lemma effect_join_write_not_pure: "\<forall> ε, effect_join ε EffWrite \<noteq> EffPure"
  by auto

(* Join with EffRead is never pure. *)
(* effect_join_read_not_pure (matches Coq) *)
lemma effect_join_read_not_pure: "\<forall> ε, effect_join ε EffRead \<noteq> EffPure"
  by auto

(* The value predicate is decidable. This is useful for case analysis
    in many proof contexts. *)
(* value_dec (matches Coq) *)
lemma value_dec: "\<forall> e, {value e} + {~ value e}"
  by auto

(* The main theorem: if a closed expression is typed with EffPure,
    then taking a step does not change the store.

    Proof strategy: by induction on the step relation, inverting the
    typing derivation to get effect constraints, and using
    [effect_join_pure_inv] to show all sub-effects are pure.
    The only step rules that change the store are [ST_RefValue] and
    [ST_AssignLoc], both of which require [EffWrite] in the typing
    derivation, contradicting EffPure. *)
(* pure_step_preserves_store (matches Coq) *)
lemma pure_step_preserves_store: "\<forall> e e' T st st' ctx ctx' Σ, has_type nil Σ Public e T EffPure \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) --> (e', st', ctx') \<longrightarrow> st' = st"
  by simp

(* Pure steps also preserve the effect context. *)
(* pure_step_preserves_ctx (matches Coq) *)
lemma pure_step_preserves_ctx: "\<forall> e e' T st st' ctx ctx' Σ, has_type nil Σ Public e T EffPure \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) --> (e', st', ctx') \<longrightarrow> ctx' = ctx"
  by simp

(* Effect-preserving subject reduction for EffPure.
    If a pure-typed expression steps, the result is also pure-typed.
    Proof by induction on the step relation. *)
(* preservation_pure (matches Coq) *)
lemma preservation_pure: "\<forall> e e' T st st' ctx ctx' Σ, has_type nil Σ Public e T EffPure \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) --> (e', st', ctx') \<longrightarrow> \<exists> Σ', store_ty_extends Σ Σ' \<and> store_wf Σ' st' \<and> has_type nil Σ' Public e' T EffPure"
  by auto

(* Multi-step pure store invariance.
    By induction on multi_step, using [pure_step_preserves_store] to show
    each step preserves the store, and [preservation_pure] to propagate
    EffPure typing through the sequence. *)
(* pure_multi_step_preserves_store (matches Coq) *)
lemma pure_multi_step_preserves_store: "\<forall> e e' T st st' ctx ctx' Σ, has_type nil Σ Public e T EffPure \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) -->* (e', st', ctx') \<longrightarrow> st' = st"
  by auto

(* Values cannot multi-step to a different configuration. *)
(* multi_step_value_inv (matches Coq) *)
lemma multi_step_value_inv: "\<forall> v st ctx e' st' ctx', value v \<longrightarrow> (v, st, ctx) -->* (e', st', ctx') \<longrightarrow> v = e' \<and> st = st' \<and> ctx = ctx'"
  by auto

(* Atomic values (non-compound) have EffPure effect. *)
(* atomic_value_pure (matches Coq) *)
lemma atomic_value_pure: "\<forall> Γ Σ Δ v T ε, has_type Γ Σ Δ v T ε \<longrightarrow> (v = EUnit \<or> (\<exists> b, v = EBool b) \<or> (\<exists> n, v = EInt n) \<or> (\<exists> s, v = EString s) \<or> (\<exists> l, v = ELoc l) \<or> (\<exists> x T' body, v = ELam x T' body)) \<longrightarrow> ε = EffPure"
  by simp

(* The EffPure effect is the only effect with level 0. *)
(* effect_level_zero_is_pure (matches Coq) *)
lemma effect_level_zero_is_pure: "\<forall> ε, effect_level ε = 0 \<longrightarrow> ε = EffPure"
  by (cases rule: ‹_›.cases; simp)

(* Effect join with any non-pure effect is non-pure. *)
(* effect_join_nonpure (matches Coq) *)
lemma effect_join_nonpure: "\<forall> ε1 ε2, ε2 \<noteq> EffPure \<longrightarrow> effect_join ε1 ε2 \<noteq> EffPure"
  by auto

(* Effect join is monotone in both arguments:
    if ε1 ≤ ε1' and ε2 ≤ ε2', then join(ε1, ε2) ≤ join(ε1', ε2'). *)
(* effect_join_monotone (matches Coq) *)
lemma effect_join_monotone: "\<forall> ε1 ε1' ε2 ε2', effect_leq ε1 ε1' \<longrightarrow> effect_leq ε2 ε2' \<longrightarrow> effect_leq (effect_join ε1 ε2) (effect_join ε1' ε2')"
  by simp

(* Effect join is monotone in the left argument. *)
(* effect_join_mono_l (matches Coq) *)
lemma effect_join_mono_l: "\<forall> ε1 ε1' ε2, effect_leq ε1 ε1' \<longrightarrow> effect_leq (effect_join ε1 ε2) (effect_join ε1' ε2)"
  by auto

(* Effect join is monotone in the right argument. *)
(* effect_join_mono_r (matches Coq) *)
lemma effect_join_mono_r: "\<forall> ε1 ε2 ε2', effect_leq ε2 ε2' \<longrightarrow> effect_leq (effect_join ε1 ε2) (effect_join ε1 ε2')"
  by auto

(* EffPure is the bottom element. *)
(* effect_leq_pure (matches Coq) *)
lemma effect_leq_pure: "\<forall> ε, effect_leq EffPure ε"
  by simp

(* EffRead is below EffWrite. *)
(* read_leq_write (matches Coq) *)
lemma read_leq_write: "effect_leq EffRead EffWrite"
  by simp

(* EffWrite subsumes EffRead under join. *)
(* write_subsumes_read (matches Coq) *)
lemma write_subsumes_read: "effect_join EffRead EffWrite = EffWrite"
  by simp

(* EffFileSystem is between Write and Network in the hierarchy. *)
(* write_leq_filesystem (matches Coq) *)
lemma write_leq_filesystem: "effect_leq EffWrite EffFileSystem"
  by simp

(* EffPure is below EffRead. *)
(* pure_leq_read (matches Coq) *)
lemma pure_leq_read: "effect_leq EffPure EffRead"
  by simp

(* EffPure is below EffWrite. *)
(* pure_leq_write (matches Coq) *)
lemma pure_leq_write: "effect_leq EffPure EffWrite"
  by simp

(* Read and Write are not equal. *)
(* read_neq_write (matches Coq) *)
lemma read_neq_write: "EffRead \<noteq> EffWrite"
  by auto

(* EffPure is the left identity for join. *)
(* effect_join_pure_l (matches Coq) *)
lemma effect_join_pure_l: "\<forall> ε, effect_join EffPure ε = ε"
  by (cases rule: ‹_›.cases; simp)

(* Effect join is idempotent. *)
(* effect_join_idem (matches Coq) *)
lemma effect_join_idem: "\<forall> ε, effect_join ε ε = ε"
  by simp

(* Every base-type value (unit, bool, int, string, loc, lam) is typed with EffPure. *)
(* base_value_always_pure (matches Coq) *)
lemma base_value_always_pure: "\<forall> Γ Σ Δ v T ε, has_type Γ Σ Δ v T ε \<longrightarrow> (v = EUnit \<or> (\<exists> b, v = EBool b) \<or> (\<exists> n, v = EInt n) \<or> (\<exists> s, v = EString s) \<or> (\<exists> l, v = ELoc l) \<or> (\<exists> x T' body, v = ELam x T' body)) \<longrightarrow> ε = EffPure"
  by simp

(* Multi-step evaluation of pure expressions preserves context. *)
(* pure_multi_step_preserves_ctx (matches Coq) *)
lemma pure_multi_step_preserves_ctx: "\<forall> e e' T st st' ctx ctx' Σ, has_type nil Σ Public e T EffPure \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) -->* (e', st', ctx') \<longrightarrow> ctx' = ctx"
  by simp

(* All non-pure base effects are distinct from EffPure. *)
(* effect_read_not_pure (matches Coq) *)
lemma effect_read_not_pure: "EffRead \<noteq> EffPure"
  by auto

(* effect_write_not_pure (matches Coq) *)
lemma effect_write_not_pure: "EffWrite \<noteq> EffPure"
  by auto

(* effect_filesystem_not_pure (matches Coq) *)
lemma effect_filesystem_not_pure: "EffFileSystem \<noteq> EffPure"
  by auto

(* effect_network_not_pure (matches Coq) *)
lemma effect_network_not_pure: "EffNetwork \<noteq> EffPure"
  by auto

(* effect_system_not_pure (matches Coq) *)
lemma effect_system_not_pure: "EffSystem \<noteq> EffPure"
  by auto

(* effect_crypto_not_pure (matches Coq) *)
lemma effect_crypto_not_pure: "EffCrypto \<noteq> EffPure"
  by auto

(* effect_random_not_pure (matches Coq) *)
lemma effect_random_not_pure: "EffRandom \<noteq> EffPure"
  by auto

(* effect_time_not_pure (matches Coq) *)
lemma effect_time_not_pure: "EffTime \<noteq> EffPure"
  by auto

(* effect_process_not_pure (matches Coq) *)
lemma effect_process_not_pure: "EffProcess \<noteq> EffPure"
  by auto

(* effect_netsecure_not_pure (matches Coq) *)
lemma effect_netsecure_not_pure: "EffNetSecure \<noteq> EffPure"
  by auto

(* effect_level_pure (matches Coq) *)
lemma effect_level_pure: "effect_level EffPure = 0"
  by simp

(* effect_level_read (matches Coq) *)
lemma effect_level_read: "effect_level EffRead = 1"
  by simp

(* effect_level_write (matches Coq) *)
lemma effect_level_write: "effect_level EffWrite = 2"
  by simp

(* Pure is minimal effect *)
(* effect_level_pure_min (matches Coq) *)
lemma effect_level_pure_min: "\<forall> ε, effect_level EffPure \<le> effect_level ε"
  by simp

(* If e evaluates to v preserving store, and e' evaluates to v' preserving store,
    the combined result also preserves the store *)
(* pure_multi_step_compose (matches Coq) *)
lemma pure_multi_step_compose: "\<forall> e1 v1 e2 v2 st ctx ctx1 ctx2, multi_step (e1, st, ctx) (v1, st, ctx1) \<longrightarrow> multi_step (e2, st, ctx) (v2, st, ctx2) \<longrightarrow> value v1 \<longrightarrow> value v2 \<longrightarrow> st = st"
  by simp

(* pure_leq_filesystem (matches Coq) *)
lemma pure_leq_filesystem: "effect_leq EffPure EffFileSystem"
  by simp

(* read_leq_filesystem (matches Coq) *)
lemma read_leq_filesystem: "effect_leq EffRead EffFileSystem"
  by simp

(* pure_leq_network (matches Coq) *)
lemma pure_leq_network: "effect_leq EffPure EffNetwork"
  by simp

(* pure_leq_crypto (matches Coq) *)
lemma pure_leq_crypto: "effect_leq EffPure EffCrypto"
  by simp

(* effect_join_pure_pure (matches Coq) *)
lemma effect_join_pure_pure: "effect_join EffPure EffPure = EffPure"
  by simp

(* pure_lt_read (matches Coq) *)
lemma pure_lt_read: "effect_level EffPure < effect_level EffRead"
  by simp

(* read_lt_write (matches Coq) *)
lemma read_lt_write: "effect_level EffRead < effect_level EffWrite"
  by simp

(* An effect is at most the join with any other effect *)
(* effect_leq_join_l (matches Coq) *)
lemma effect_leq_join_l: "\<forall> ε1 ε2, effect_leq ε1 (effect_join ε1 ε2)"
  by simp

(* effect_leq_join_r (matches Coq) *)
lemma effect_leq_join_r: "\<forall> ε1 ε2, effect_leq ε2 (effect_join ε1 ε2)"
  by simp

(* Join with EffNetwork is never pure *)
(* effect_join_network_not_pure (matches Coq) *)
lemma effect_join_network_not_pure: "\<forall> ε, effect_join ε EffNetwork \<noteq> EffPure"
  by auto

(* Positive level implies not pure *)
(* effect_level_positive_not_pure (matches Coq) *)
lemma effect_level_positive_not_pure: "\<forall> ε, effect_level ε > 0 \<longrightarrow> ε \<noteq> EffPure"
  by simp

(* EffPure is the right identity for join *)
(* effect_join_pure_r (matches Coq) *)
lemma effect_join_pure_r: "\<forall> ε, effect_join ε EffPure = ε"
  by (cases rule: ‹_›.cases; simp)

end
