(* Copyright (c) 2026 The RIINA Authors. All rights reserved. *)

(*
 * RIINA TypeSafety - Isabelle/HOL Port
 *
 * Auto-generated port of 02_FORMAL/coq/type_system/TypeSafety.v (6 theorems).
 *
 * Generated by scripts/generate-multiprover.py
 *
 * Correspondence Table:
 *
 * | Coq Definition     | Isabelle Definition    | Status |
 * |--------------------|------------------------|--------|
 * | stuck              | stuck                  | OK     |
 * | type_safety        | type_safety            | OK     |
 * | multi_step_safety  | multi_step_safety      | OK     |
 * | stuck_implies_not_value | stuck_implies_not_value | OK     |
 * | stuck_implies_not_stepping | stuck_implies_not_stepping | OK     |
 * | not_stuck_from_value_or_step | not_stuck_from_value_or_step | OK     |
 * | stuck_complete     | stuck_complete         | OK     |
 *)

theory TypeSafety
  imports Main
begin

(* stuck (matches Coq: Definition stuck) *)
definition stuck :: "bool" where
  "stuck \<equiv> let '(e, st, ctx) := cfg in
  ~ value e /\ ~ exists cfg', cfg --> cfg'"

(* type_safety (matches Coq) *)
lemma type_safety: "\<forall> e T ε st ctx Σ, has_type nil Σ Public e T ε \<longrightarrow> store_wf Σ st \<longrightarrow> ~ stuck (e, st, ctx)"
  by auto

(* Multi-step safety: well-typed terms stay well-typed after any
    number of steps. This is a direct consequence of preservation. *)
(* multi_step_safety (matches Coq) *)
lemma multi_step_safety: "\<forall> e e' T ε st st' ctx ctx' Σ, has_type nil Σ Public e T ε \<longrightarrow> store_wf Σ st \<longrightarrow> (e, st, ctx) -->* (e', st', ctx') \<longrightarrow> \<exists> Σ', store_wf Σ' st' \<and> ~ stuck (e', st', ctx')"
  by auto

(* If stuck, not a value *)
(* stuck_implies_not_value (matches Coq) *)
lemma stuck_implies_not_value: "\<forall> e st ctx, stuck (e, st, ctx) \<longrightarrow> ~ value e"
  by auto

(* If stuck, cannot step *)
(* stuck_implies_not_stepping (matches Coq) *)
lemma stuck_implies_not_stepping: "\<forall> e st ctx, stuck (e, st, ctx) \<longrightarrow> ~ \<exists> cfg', (e, st, ctx) --> cfg'"
  by auto

(* Value or stepping implies not stuck *)
(* not_stuck_from_value_or_step (matches Coq) *)
lemma not_stuck_from_value_or_step: "\<forall> e st ctx, (value e \<or> \<exists> e' st' ctx', (e, st, ctx) --> (e', st', ctx')) \<longrightarrow> ~ stuck (e, st, ctx)"
  by auto

(* Stuck implies neither value nor stepping — constructive version *)
(* stuck_complete (matches Coq) *)
lemma stuck_complete: "\<forall> e st ctx, stuck (e, st, ctx) \<longrightarrow> ~ value e \<and> ~ \<exists> e' st' ctx', (e, st, ctx) --> (e', st', ctx')"
  by auto

end
