-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.

/-!
# RIINA IndustryHealthcare - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/Industries/IndustryHealthcare.v (29 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| PHI_Category | PHI_Category | OK |
| HealthcareEffect | HealthcareEffect | OK |
| HIPAA_Policy | HIPAA_Policy | OK |
| BreakGlassEvent | BreakGlassEvent | OK |
| ConsentRecord | ConsentRecord | OK |
| phi_sensitivity | phi_sensitivity | OK |
| minimum_necessary | minimum_necessary | OK |
| hipaa_all_controls | hipaa_all_controls | OK |
| hipaa_security_minimum | hipaa_security_minimum | OK |
| role_level | role_level | OK |
| access_permitted | access_permitted | OK |
| consent_valid | consent_valid | OK |
| retention_years | retention_years | OK |
| deidentified_sensitivity | deidentified_sensitivity | OK |
| dose_in_range | dose_in_range | OK |
| lab_in_normal_range | lab_in_normal_range | OK |
| hipaa_privacy_rule | hipaa_privacy_rule | OK |
| hipaa_security_rule | hipaa_security_rule | OK |
| fda_21_cfr_11 | fda_21_cfr_11 | OK |
| hitech_breach_notification | hitech_breach_notification | OK |
| hl7_fhir_security | hl7_fhir_security | OK |
| phi_encryption_required | phi_encryption_required | OK |
| minimum_necessary_access | minimum_necessary_access | OK |
| phi_sensitivity_positive | phi_sensitivity_positive | OK |
| max_sensitivity_categories | max_sensitivity_categories | OK |
| demographics_minimum | demographics_minimum | OK |
| genetic_sensitivity_ordering | genetic_sensitivity_ordering | OK |
| hipaa_all_controls_access | hipaa_all_controls_access | OK |
| hipaa_all_controls_audit | hipaa_all_controls_audit | OK |
| hipaa_all_controls_integrity | hipaa_all_controls_integrity | OK |
| hipaa_all_controls_transmission | hipaa_all_controls_transmission | OK |
| hipaa_all_controls_encryption | hipaa_all_controls_encryption | OK |
| hipaa_full_implies_minimum | hipaa_full_implies_minimum | OK |
| break_glass_must_be_logged | break_glass_must_be_logged | OK |
| high_role_accesses_demographics | high_role_accesses_demographics | OK |
| low_role_denied_psychotherapy | low_role_denied_psychotherapy | OK |
| role_sufficient_access | role_sufficient_access | OK |
| consent_expired_invalid | consent_expired_invalid | OK |
| consent_not_granted_invalid | consent_not_granted_invalid | OK |
| retention_minimum_6_years | retention_minimum_6_years | OK |
| genetic_longest_retention | genetic_longest_retention | OK |
| deidentification_removes_sensitivity | deidentification_removes_sensitivity | OK |
| non_deidentified_preserves_sensitivity | non_deidentified_preserves_sensitivity | OK |
| dose_range_valid | dose_range_valid | OK |
| lab_range_bounded | lab_range_bounded | OK |
-/

namespace RIINA

/-- Coq compatibility shim: boolean negation -/
@[inline] def negb (b : Bool) : Bool := !b
/-- Coq compatibility shim: boolean conjunction -/
@[inline] def andb (a b : Bool) : Bool := a && b
/-- Coq compatibility shim: boolean disjunction -/
@[inline] def orb (a b : Bool) : Bool := a || b
/-- Coq compatibility shim: list universal predicate -/
@[inline] def forallb {α : Type} (f : α → Bool) (xs : List α) : Bool := xs.all f
/-- Coq compatibility shim: list existential predicate -/
@[inline] def existsb {α : Type} (f : α → Bool) (xs : List α) : Bool := xs.any f
/-- Coq compatibility shim: list length alias -/
@[inline] def length {α : Type} (xs : List α) : Nat := xs.length
/-- Coq compatibility shim: list head option -/
@[inline] def hd_error {α : Type} (xs : List α) : Option α := xs.head?
/-- Coq compatibility shim: list find option -/
@[inline] def find {α : Type} (p : α → Bool) (xs : List α) : Option α := xs.find? p
/-- Coq compatibility shim: pair first projection -/
@[inline] def fst {α β : Type} (p : α × β) : α := p.1
/-- Coq compatibility shim: pair second projection -/
@[inline] def snd {α β : Type} (p : α × β) : β := p.2

/-- Boolean conjunction iff (matches Coq: andb_true_iff) -/
private theorem andb_true_iff (a b : Bool) :
    (a && b) = true ↔ a = true ∧ b = true := by
  constructor
  · intro h; cases a <;> cases b <;> simp_all
  · intro ⟨ha, hb⟩; simp [ha, hb]

/-- PHI_Category (matches Coq: Inductive PHI_Category) -/
inductive PHI_Category where
  | Demographics : PHI_Category
  | MedicalRecord : PHI_Category
  | Psychotherapy : PHI_Category
  | Genetic : PHI_Category
  | Substance : PHI_Category
  | HIV_Status : PHI_Category
  deriving DecidableEq, Repr

/-- HealthcareEffect (matches Coq: Inductive HealthcareEffect) -/
inductive HealthcareEffect where
  | PHI_Access : PHI_Category → HealthcareEffect
  | EHR_Write : HealthcareEffect
  | Prescription : HealthcareEffect
  | LabResult : HealthcareEffect
  | ClinicalDecision : HealthcareEffect
  deriving DecidableEq, Repr

/-- HIPAA_Policy (matches Coq: Record HIPAA_Policy) -/
structure HIPAA_Policy where
  access_control : Bool
  audit_controls : Bool
  integrity_controls : Bool
  transmission_security : Bool
  encryption_at_rest : Bool
  deriving DecidableEq, Repr
/-- Coq constructor alias for HIPAA_Policy. -/
abbrev mkHIPAAPolicy := HIPAA_Policy.mk

/-- BreakGlassEvent (matches Coq: Record BreakGlassEvent) -/
structure BreakGlassEvent where
  bg_accessor : Nat
  bg_patient : Nat
  bg_timestamp : Nat
  bg_reason : Nat
  bg_logged : Bool
  deriving DecidableEq, Repr
/-- Coq constructor alias for BreakGlassEvent. -/
abbrev mkBreakGlass := BreakGlassEvent.mk

/-- ConsentRecord (matches Coq: Record ConsentRecord) -/
structure ConsentRecord where
  consent_patient : Nat
  consent_purpose : Nat
  consent_granted : Bool
  consent_timestamp : Nat
  consent_expiry : Nat
  deriving DecidableEq, Repr
/-- Coq constructor alias for ConsentRecord. -/
abbrev mkConsent := ConsentRecord.mk

/-- phi_sensitivity (matches Coq: Definition phi_sensitivity) -/
def phi_sensitivity (cat : PHI_Category) : Nat :=
  match cat with
  | Demographics => 1
  | MedicalRecord => 2
  | Psychotherapy => 4
  | Genetic => 3
  | Substance => 4
  | HIV_Status => 4

/-- minimum_necessary (matches Coq: Definition minimum_necessary) -/
def minimum_necessary (requested : List PHI_Category) (required : List PHI_Category) : Bool :=
  match r, req with
  | x, y => true

/-- hipaa_all_controls (matches Coq: Definition hipaa_all_controls) -/
def hipaa_all_controls : HIPAA_Policy := mkHIPAAPolicy true true true true true

/-- hipaa_security_minimum (matches Coq: Definition hipaa_security_minimum) -/
def hipaa_security_minimum (p : HIPAA_Policy) : Bool :=
  access_control p && audit_controls p

/-- role_level (matches Coq: Definition role_level) -/
def role_level (role : Nat) : Nat :=
  role

/-- access_permitted (matches Coq: Definition access_permitted) -/
def access_permitted (role_lvl : Nat) (cat : PHI_Category) : Bool :=
  Nat.leb (phi_sensitivity cat) role_lvl

/-- consent_valid (matches Coq: Definition consent_valid) -/
def consent_valid (c : ConsentRecord) (current_time : Nat) : Bool :=
  consent_granted c && Nat.ltb current_time (consent_expiry c)

/-- retention_years (matches Coq: Definition retention_years) -/
def retention_years (cat : PHI_Category) : Nat :=
  match cat with
  | Demographics => 6
  | MedicalRecord => 10
  | Psychotherapy => 10
  | Genetic => 25
  | Substance => 10
  | HIV_Status => 10

/-- deidentified_sensitivity (matches Coq: Definition deidentified_sensitivity) -/
def deidentified_sensitivity (is_deidentified : Bool) (cat : PHI_Category) : Nat :=
  if is_deidentified then 0 else phi_sensitivity cat

/-- dose_in_range (matches Coq: Definition dose_in_range) -/
def dose_in_range (dose min_dose max_dose : Nat) : Bool :=
  Nat.leb min_dose dose && Nat.leb dose max_dose

/-- lab_in_normal_range (matches Coq: Definition lab_in_normal_range) -/
def lab_in_normal_range (value low high : Nat) : Bool :=
  Nat.leb low value && Nat.leb value high

-- Section B01 - HIPAA Privacy Rule
    Reference: IND_B_HEALTHCARE.md Section 3.1
    Psychotherapy notes have maximum sensitivity (level 4).
/-- hipaa_privacy_rule (matches Coq) -/
theorem hipaa_privacy_rule : phi_sensitivity Psychotherapy = 4 := by
  rfl

-- Section B02 - HIPAA Security Rule
    Reference: IND_B_HEALTHCARE.md Section 3.2
    All four required security controls together form a valid conjunction.
/-- hipaa_security_rule (matches Coq) -/
theorem hipaa_security_rule : ∀ (policy : HIPAA_Policy), access_control policy = true → audit_controls policy = true → integrity_controls policy = true → transmission_security policy = true → access_control policy && audit_controls policy && integrity_controls policy && transmission_security policy = true := by
  rfl

-- Section B03 - FDA 21 CFR Part 11
    Reference: IND_B_HEALTHCARE.md Section 3.3
    Demographics has the minimum PHI sensitivity (level 1).
/-- fda_21_cfr_11 (matches Coq) -/
theorem fda_21_cfr_11 : phi_sensitivity Demographics = 1 := by
  rfl

-- Section B04 - HITECH Breach Notification
    Reference: IND_B_HEALTHCARE.md Section 3.4
    HIV status has maximum sensitivity — same level as Psychotherapy.
/-- hitech_breach_notification (matches Coq) -/
theorem hitech_breach_notification : phi_sensitivity HIV_Status = phi_sensitivity Psychotherapy := by
  rfl

-- Section B05 - HL7 FHIR Security
    Reference: IND_B_HEALTHCARE.md Section 3.5
    Substance abuse records have maximum sensitivity (level 4).
/-- hl7_fhir_security (matches Coq) -/
theorem hl7_fhir_security : phi_sensitivity Substance = 4 := by
  rfl

-- PHI must be encrypted in transit:
    If transmission security is enabled, its negation is false.
/-- phi_encryption_required (matches Coq) -/
theorem phi_encryption_required : ∀ (policy : HIPAA_Policy), transmission_security policy = true → negb (transmission_security policy) = false := by
  rfl

-- Minimum necessary access:
    If minimum_necessary check passes, the result is consistently true.
/-- minimum_necessary_access (matches Coq) -/
theorem minimum_necessary_access : ∀ phi_requested treatment_required, minimum_necessary phi_requested treatment_required = true → negb (minimum_necessary phi_requested treatment_required) = false := by
  rfl

-- Sensitivity ordering
/-- phi_sensitivity_positive (matches Coq) -/
theorem phi_sensitivity_positive : ∀ cat, phi_sensitivity cat ≥ 1 := by
  cases ‹_› <;> simp <;> omega

-- Psychotherapy, Substance, HIV all have maximum sensitivity
/-- max_sensitivity_categories (matches Coq) -/
theorem max_sensitivity_categories : ∀ cat, cat = Psychotherapy ∨ cat = Substance ∨ cat = HIV_Status → phi_sensitivity cat = 4 := by
  cases ‹_› <;> simp

-- Demographics has minimum sensitivity
/-- demographics_minimum (matches Coq) -/
theorem demographics_minimum : ∀ cat, phi_sensitivity Demographics ≤ phi_sensitivity cat := by
  cases ‹_› <;> simp <;> omega

-- Genetic data is less sensitive than psychotherapy but more than medical records
/-- genetic_sensitivity_ordering (matches Coq) -/
theorem genetic_sensitivity_ordering : phi_sensitivity MedicalRecord < phi_sensitivity Genetic ∧ phi_sensitivity Genetic < phi_sensitivity Psychotherapy := by
  omega

/-- hipaa_all_controls_access (matches Coq) -/
theorem hipaa_all_controls_access : access_control hipaa_all_controls = true := by
  simp

/-- hipaa_all_controls_audit (matches Coq) -/
theorem hipaa_all_controls_audit : audit_controls hipaa_all_controls = true := by
  simp

/-- hipaa_all_controls_integrity (matches Coq) -/
theorem hipaa_all_controls_integrity : integrity_controls hipaa_all_controls = true := by
  simp

/-- hipaa_all_controls_transmission (matches Coq) -/
theorem hipaa_all_controls_transmission : transmission_security hipaa_all_controls = true := by
  simp

/-- hipaa_all_controls_encryption (matches Coq) -/
theorem hipaa_all_controls_encryption : encryption_at_rest hipaa_all_controls = true := by
  simp

-- Full security implies minimum
/-- hipaa_full_implies_minimum (matches Coq) -/
theorem hipaa_full_implies_minimum : ∀ p, access_control p = true → audit_controls p = true → integrity_controls p = true → transmission_security p = true → hipaa_security_minimum p = true := by
  simp

/-- break_glass_must_be_logged (matches Coq) -/
theorem break_glass_must_be_logged : ∀ evt, bg_logged evt = true → bg_logged evt ≠ false := by
  simp_all [Bool.and_eq_true]

/-- high_role_accesses_demographics (matches Coq) -/
theorem high_role_accesses_demographics : ∀ r, r ≥ 1 → access_permitted r Demographics = true := by
  omega

/-- low_role_denied_psychotherapy (matches Coq) -/
theorem low_role_denied_psychotherapy : access_permitted 2 Psychotherapy = false := by
  simp

-- Sufficient role level grants access
/-- role_sufficient_access (matches Coq) -/
theorem role_sufficient_access : ∀ r cat, r ≥ phi_sensitivity cat → access_permitted r cat = true := by
  simp_all [Bool.and_eq_true]

/-- consent_expired_invalid (matches Coq) -/
theorem consent_expired_invalid : ∀ c t, Nat.ltb t (consent_expiry c) = false → consent_valid c t = false := by
  simp_all [Bool.and_eq_true]

/-- consent_not_granted_invalid (matches Coq) -/
theorem consent_not_granted_invalid : ∀ c t, consent_granted c = false → consent_valid c t = false := by
  simp

/-- retention_minimum_6_years (matches Coq) -/
theorem retention_minimum_6_years : ∀ cat, retention_years cat ≥ 6 := by
  cases ‹_› <;> simp <;> omega

/-- genetic_longest_retention (matches Coq) -/
theorem genetic_longest_retention : ∀ cat, retention_years cat ≤ retention_years Genetic := by
  cases ‹_› <;> simp <;> omega

/-- deidentification_removes_sensitivity (matches Coq) -/
theorem deidentification_removes_sensitivity : ∀ cat, deidentified_sensitivity true cat = 0 := by
  rfl

/-- non_deidentified_preserves_sensitivity (matches Coq) -/
theorem non_deidentified_preserves_sensitivity : ∀ cat, deidentified_sensitivity false cat = phi_sensitivity cat := by
  rfl

/-- dose_range_valid (matches Coq) -/
theorem dose_range_valid : ∀ dose min_d max_d, dose_in_range dose min_d max_d = true → min_d ≤ dose ∧ dose ≤ max_d := by
  simp_all [Bool.and_eq_true]

/-- lab_range_bounded (matches Coq) -/
theorem lab_range_bounded : ∀ v lo hi, lab_in_normal_range v lo hi = true → lo ≤ v ∧ v ≤ hi := by
  simp_all [Bool.and_eq_true]

end RIINA
