// Copyright (c) 2026 The RIINA Authors. All rights reserved.
// Copyright (c) 2026 The RIINA Authors.
// Auto-generated from 02_FORMAL/coq/domains/QuantitativeDeclassification.v (22 assertions)
// Generated by scripts/generate-full-stack.py
module riina/domains/quantitative_declassification

open util/boolean

// level (matches Coq: Inductive level)
abstract sig level {}
one sig Low extends level {}
one sig High extends level {}

// expr (matches Coq: Inductive expr)
abstract sig expr {}
one sig EConst extends expr {}
one sig EVar extends expr {}
one sig EPlus extends expr {}
one sig EDeclass extends expr {}

// level_leq (matches Coq: Definition level_leq)
pred level_leq {}

// level_join (matches Coq: Definition level_join)
pred level_join {}

// low_equiv (matches Coq: Definition low_equiv)
pred low_equiv {}

// 1 (matches Coq: Theorem 1)
assert 1 {
  all x: level | x in level
}
check 1 for 5

// 2 (matches Coq: Theorem 2)
assert 2 {
  all x: level | x in level
}
check 2 for 5

// 3 (matches Coq: Theorem 3)
assert 3 {
  all x: level | x in level
}
check 3 for 5

// 4 (matches Coq: Theorem 4)
assert 4 {
  all x: level | x in level
}
check 4 for 5

// 5 (matches Coq: Theorem 5)
assert 5 {
  all x: level | x in level
}
check 5 for 5

// 6 (matches Coq: Theorem 6)
assert 6 {
  all x: level | x in level
}
check 6 for 5

// 7 (matches Coq: Theorem 7)
assert 7 {
  all x: level | x in level
}
check 7 for 5

// 8 (matches Coq: Theorem 8)
assert 8 {
  all x: level | x in level
}
check 8 for 5

// 9 (matches Coq: Theorem 9)
assert 9 {
  all x: level | x in level
}
check 9 for 5

// 10 (matches Coq: Theorem 10)
assert 10 {
  all x: level | x in level
}
check 10 for 5

// 11 (matches Coq: Theorem 11)
assert 11 {
  all x: level | x in level
}
check 11 for 5

// 12 (matches Coq: Theorem 12)
assert 12 {
  all x: level | x in level
}
check 12 for 5

// 13 (matches Coq: Theorem 13)
assert 13 {
  all x: level | x in level
}
check 13 for 5

// 14 (matches Coq: Theorem 14)
assert 14 {
  all x: level | x in level
}
check 14 for 5

// 15 (matches Coq: Theorem 15)
assert 15 {
  all x: level | x in level
}
check 15 for 5

// 16 (matches Coq: Theorem 16)
assert 16 {
  all x: level | x in level
}
check 16 for 5

// 17 (matches Coq: Theorem 17)
assert 17 {
  all x: level | x in level
}
check 17 for 5

// 18 (matches Coq: Theorem 18)
assert 18 {
  all x: level | x in level
}
check 18 for 5

// 19 (matches Coq: Theorem 19)
assert 19 {
  all x: level | x in level
}
check 19 for 5

// 20 (matches Coq: Theorem 20)
assert 20 {
  all x: level | x in level
}
check 20 for 5

// 21 (matches Coq: Theorem 21)
assert 21 {
  all x: level | x in level
}
check 21 for 5

// 22 (matches Coq: Theorem 22)
assert 22 {
  all x: level | x in level
}
check 22 for 5
