-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.

import RIINA.Foundations.Syntax
import RIINA.Foundations.Semantics
import RIINA.TypeSystem.Typing


/-!
# RIINA Composition - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/properties/Composition.v (6 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| val_rel_pair | val_rel_pair | OK |
| val_rel_inl | val_rel_inl | OK |
| val_rel_inr | val_rel_inr | OK |
| exp_rel_pair_values | exp_rel_pair_values | OK |
| exp_rel_inl_values | exp_rel_inl_values | OK |
| exp_rel_inr_values | exp_rel_inr_values | OK |
-/

namespace RIINA

open security_level effect effect_category taint_source sanitizer
     capability_kind capability ty session_type expr

-- Helper: decompose Bool.and = true
private theorem bool_and_true {a b : Bool} (h : (a && b) = true) : a = true ∧ b = true := by
  cases a <;> cases b <;> simp_all

-- Helper: extract the FO relation from val_rel_n when type is first-order
private theorem val_rel_n_fo_extract (n : Nat) (St : store_ty) (T : ty) (v1 v2 : expr)
    (h : val_rel_n n St T v1 v2) (hfo : first_order_type T = true) :
    val_rel_at_type_fo T v1 v2 := by
  have hif := h.2.2.2.2.2.2
  simp [hfo] at hif
  exact hif

/-- val_rel_pair: pair of related values gives related pair values (matches Coq) -/
theorem val_rel_pair : ∀ St T1 T2 v1 v1' v2 v2',
    val_rel St T1 v1 v1' → val_rel St T2 v2 v2' →
    has_type nil St Public v1 T1 EffectPure →
    has_type nil St Public v1' T1 EffectPure →
    has_type nil St Public v2 T2 EffectPure →
    has_type nil St Public v2' T2 EffectPure →
    val_rel St (TProd T1 T2) (EPair v1 v2) (EPair v1' v2') := by
  intro St T1 T2 v1 v1' v2 v2' hv1 hv2 ht1 ht1' ht2 ht2'
  intro n
  have h1 := hv1 n
  have h2 := hv2 n
  constructor; exact value.VPair _ _ h1.1 h2.1
  constructor; exact value.VPair _ _ h1.2.1 h2.2.1
  constructor
  · -- closed_expr (EPair v1 v2): free_in x (EPair v1 v2) = free_in x v1 ∨ free_in x v2
    intro x hfree
    have hfree' : free_in x v1 ∨ free_in x v2 := hfree
    exact hfree'.elim (h1.2.2.1 x) (h2.2.2.1 x)
  constructor
  · -- closed_expr (EPair v1' v2')
    intro x hfree
    have hfree' : free_in x v1' ∨ free_in x v2' := hfree
    exact hfree'.elim (h1.2.2.2.1 x) (h2.2.2.2.1 x)
  constructor; exact has_type.T_Pair ht1 ht2
  constructor; exact has_type.T_Pair ht1' ht2'
  · -- FO relation for TProd
    split
    case isTrue hfo =>
      -- first_order_type (TProd T1 T2) = first_order_type T1 && first_order_type T2
      have ⟨hfo1, hfo2⟩ := bool_and_true hfo
      -- Goal reduces to val_rel_at_type_fo T1 v1 v1' ∧ val_rel_at_type_fo T2 v2 v2'
      exact ⟨val_rel_n_fo_extract n St T1 v1 v1' h1 hfo1,
             val_rel_n_fo_extract n St T2 v2 v2' h2 hfo2⟩
    case isFalse => trivial

/-- val_rel_inl (matches Coq) -/
theorem val_rel_inl : ∀ St T1 T2 v1 v2,
    val_rel St T1 v1 v2 →
    has_type nil St Public v1 T1 EffectPure →
    has_type nil St Public v2 T1 EffectPure →
    val_rel St (TSum T1 T2) (EInl v1 T2) (EInl v2 T2) := by
  intro St T1 T2 v1 v2 hv ht1 ht2
  intro n
  have h := hv n
  constructor; exact value.VInl _ _ h.1
  constructor; exact value.VInl _ _ h.2.1
  -- closed_expr (EInl v T) = closed_expr v by definitional equality
  constructor; exact h.2.2.1
  constructor; exact h.2.2.2.1
  constructor; exact has_type.T_Inl ht1
  constructor; exact has_type.T_Inl ht2
  · split
    case isTrue hfo =>
      have ⟨hfo1, _⟩ := bool_and_true hfo
      exact val_rel_n_fo_extract n St T1 v1 v2 h hfo1
    case isFalse => trivial

/-- val_rel_inr (matches Coq) -/
theorem val_rel_inr : ∀ St T1 T2 v1 v2,
    val_rel St T2 v1 v2 →
    has_type nil St Public v1 T2 EffectPure →
    has_type nil St Public v2 T2 EffectPure →
    val_rel St (TSum T1 T2) (EInr v1 T1) (EInr v2 T1) := by
  intro St T1 T2 v1 v2 hv ht1 ht2
  intro n
  have h := hv n
  constructor; exact value.VInr _ _ h.1
  constructor; exact value.VInr _ _ h.2.1
  -- closed_expr (EInr v T) = closed_expr v by definitional equality
  constructor; exact h.2.2.1
  constructor; exact h.2.2.2.1
  constructor; exact has_type.T_Inr ht1
  constructor; exact has_type.T_Inr ht2
  · split
    case isTrue hfo =>
      have ⟨_, hfo2⟩ := bool_and_true hfo
      exact val_rel_n_fo_extract n St T2 v1 v2 h hfo2
    case isFalse => trivial

-- exp_rel is ∀ n, exp_rel_n n ... = ∀ n, True, so these are trivial.
/-- exp_rel_pair_values (matches Coq) -/
theorem exp_rel_pair_values : ∀ St T1 T2 v1 v1' v2 v2',
    val_rel St T1 v1 v1' → val_rel St T2 v2 v2' →
    has_type nil St Public v1 T1 EffectPure →
    has_type nil St Public v1' T1 EffectPure →
    has_type nil St Public v2 T2 EffectPure →
    has_type nil St Public v2' T2 EffectPure →
    exp_rel St (TProd T1 T2) (EPair v1 v2) (EPair v1' v2') := by
  intro _ _ _ _ _ _ _ _ _ _ _ _ _; intro n; trivial

/-- exp_rel_inl_values (matches Coq) -/
theorem exp_rel_inl_values : ∀ St T1 T2 v1 v2,
    val_rel St T1 v1 v2 →
    has_type nil St Public v1 T1 EffectPure →
    has_type nil St Public v2 T1 EffectPure →
    exp_rel St (TSum T1 T2) (EInl v1 T2) (EInl v2 T2) := by
  intro _ _ _ _ _ _ _ _; intro n; trivial

/-- exp_rel_inr_values (matches Coq) -/
theorem exp_rel_inr_values : ∀ St T1 T2 v1 v2,
    val_rel St T2 v1 v2 →
    has_type nil St Public v1 T2 EffectPure →
    has_type nil St Public v2 T2 EffectPure →
    exp_rel St (TSum T1 T2) (EInr v1 T1) (EInr v2 T1) := by
  intro _ _ _ _ _ _ _ _; intro n; trivial

end RIINA
