-- Copyright (c) 2026 The RIINA Authors. All rights reserved.
-- Copyright (c) 2026 The RIINA Authors. See AUTHORS file.
import RIINA.Foundations.Syntax
import RIINA.Foundations.Semantics
import RIINA.TypeSystem.Typing

/-!
# RIINA TypeMeasure - Lean 4 Port

Auto-generated port of 02_FORMAL/coq/properties/TypeMeasure.v (50 theorems).

Generated by scripts/generate-multiprover.py

## Correspondence Table

| Coq Definition | Lean Definition | Status |
|----------------|-----------------|--------|
| ty_size | ty_size | OK |
| ty_size_lt | ty_size_lt | OK |
| first_order_type | first_order_type | OK |
| fo_compound_depth | fo_compound_depth | OK |
| ty_depth | ty_depth | OK |
| step_ty_measure | step_ty_measure | OK |
| ty_size_pos | ty_size_pos | OK |
| ty_size_fn_arg | ty_size_fn_arg | OK |
| ty_size_fn_res | ty_size_fn_res | OK |
| ty_size_prod_left | ty_size_prod_left | OK |
| ty_size_prod_right | ty_size_prod_right | OK |
| ty_size_sum_left | ty_size_sum_left | OK |
| ty_size_sum_right | ty_size_sum_right | OK |
| ty_size_ref_content | ty_size_ref_content | OK |
| ty_size_secret_content | ty_size_secret_content | OK |
| ty_size_proof_content | ty_size_proof_content | OK |
| ty_size_lt_wf | ty_size_lt_wf | OK |
| ty_size_induction | ty_size_induction | OK |
| first_order_no_fn | first_order_no_fn | OK |
| first_order_decidable | first_order_decidable | OK |
| first_order_prod_inv | first_order_prod_inv | OK |
| first_order_sum_inv | first_order_sum_inv | OK |
| first_order_ref_inv | first_order_ref_inv | OK |
| first_order_secret_inv | first_order_secret_inv | OK |
| first_order_proof_inv | first_order_proof_inv | OK |
| fo_compound_depth_prod | fo_compound_depth_prod | OK |
| fo_compound_depth_sum | fo_compound_depth_sum | OK |
| fo_compound_depth_prod_left | fo_compound_depth_prod_left | OK |
| fo_compound_depth_prod_right | fo_compound_depth_prod_right | OK |
| fo_compound_depth_sum_left | fo_compound_depth_sum_left | OK |
| fo_compound_depth_sum_right | fo_compound_depth_sum_right | OK |
| fo_compound_depth_primitive | fo_compound_depth_primitive | OK |
| ty_depth_fn_arg | ty_depth_fn_arg | OK |
| ty_depth_fn_res | ty_depth_fn_res | OK |
| first_order_base_depth | first_order_base_depth | OK |
| ty_size_list | ty_size_list | OK |
| ty_size_option | ty_size_option | OK |
| ty_size_labeled | ty_size_labeled | OK |
| ty_size_tainted | ty_size_tainted | OK |
| ty_size_sanitized | ty_size_sanitized | OK |
| ty_size_constant_time | ty_size_constant_time | OK |
| ty_size_zeroizing | ty_size_zeroizing | OK |
| ty_depth_prod_left | ty_depth_prod_left | OK |
| ty_depth_prod_right | ty_depth_prod_right | OK |
| ty_depth_sum_left | ty_depth_sum_left | OK |
| ty_depth_sum_right | ty_depth_sum_right | OK |
| first_order_list_inv | first_order_list_inv | OK |
| first_order_option_inv | first_order_option_inv | OK |
| first_order_labeled_inv | first_order_labeled_inv | OK |
| first_order_constant_time_inv | first_order_constant_time_inv | OK |
| first_order_zeroizing_inv | first_order_zeroizing_inv | OK |
| ty_depth_nonneg | ty_depth_nonneg | OK |
| ty_depth_fn_positive | ty_depth_fn_positive | OK |
| ty_depth_prod_positive | ty_depth_prod_positive | OK |
| ty_depth_sum_positive | ty_depth_sum_positive | OK |
| ty_depth_secret_positive | ty_depth_secret_positive | OK |
-/

namespace RIINA

open security_level effect effect_category taint_source sanitizer
     capability_kind capability ty session_type expr

/-- Coq compatibility alias (private to avoid collision with LexOrder). -/
private abbrev well_founded {α : Sort _} (r : α → α → Prop) := WellFounded r

-- Coq compatibility shims imported from RIINA.Foundations.Typing

/-- Boolean conjunction iff (matches Coq: andb_true_iff) -/
private theorem andb_true_iff (a b : Bool) :
    (a && b) = true ↔ a = true ∧ b = true := by
  constructor
  · intro h; cases a <;> cases b <;> simp_all
  · intro ⟨ha, hb⟩; simp [ha, hb]

private theorem one_add_pos (n : Nat) : 0 < 1 + n := by
  simpa [Nat.add_comm, Nat.succ_eq_add_one] using (Nat.succ_pos n)

-- `ty_size`, `first_order_type`, and `fo_compound_depth` are defined in
-- RIINA.Foundations.Syntax and reused here.

/-- ty_size_lt (matches Coq: Definition ty_size_lt) -/
def ty_size_lt (T1 T2 : ty) : Prop :=
  ty_size T1 < ty_size T2

/-- ty_depth (matches Coq: Definition ty_depth) -/
def ty_depth (T : ty) : Nat :=
  match T with
  | TUnit => 0
  | TBool => 0
  | TInt => 0
  | TString => 0
  | TBytes => 0
  | TFn T1 T2 _ => 1 + Nat.max (ty_depth T1) (ty_depth T2)
  | TProd T1 T2 => 1 + Nat.max (ty_depth T1) (ty_depth T2)
  | TSum T1 T2 => 1 + Nat.max (ty_depth T1) (ty_depth T2)
  | TList T' => 1 + ty_depth T'
  | TOption T' => 1 + ty_depth T'
  | TRef T' _ => 1 + ty_depth T'
  | TSecret T' => 1 + ty_depth T'
  | TLabeled T' _ => 1 + ty_depth T'
  | TTainted T' _ => 1 + ty_depth T'
  | TSanitized T' _ => 1 + ty_depth T'
  | TProof T' => 1 + ty_depth T'
  | TCapability _ => 0
  | TCapabilityFull _ => 0
  | TChan _ => 0
  | TSecureChan _ _ => 0
  | TConstantTime T' => 1 + ty_depth T'
  | TZeroizing T' => 1 + ty_depth T'

/-- step_ty_measure (matches Coq: Definition step_ty_measure) -/
def step_ty_measure (n : Nat) (T : ty) : Nat × Nat :=
  (n, ty_size T)

/-- ty_size_pos (matches Coq) -/
theorem ty_size_pos : ∀ T, ty_size T > 0 := by
  intro T
  cases T <;> simp [ty_size, one_add_pos, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]

-- TFn argument is strictly smaller
/-- ty_size_fn_arg (matches Coq) -/
theorem ty_size_fn_arg : ∀ T1 T2 eff, ty_size T1 < ty_size (TFn T1 T2 eff) := by
  intro T1 T2 eff
  have h1 : ty_size T1 < ty_size T1 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T1 + 1 ≤ ty_size T1 + 1 + ty_size T2 :=
    Nat.le_add_right _ _
  have h2' : ty_size T1 + 1 ≤ ty_size (TFn T1 T2 eff) := by
    simpa [ty_size, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TFn result is strictly smaller
/-- ty_size_fn_res (matches Coq) -/
theorem ty_size_fn_res : ∀ T1 T2 eff, ty_size T2 < ty_size (TFn T1 T2 eff) := by
  intro T1 T2 eff
  have h1 : ty_size T2 < ty_size T2 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T2 + 1 ≤ ty_size T2 + 1 + ty_size T1 :=
    Nat.le_add_right _ _
  have h2' : ty_size T2 + 1 ≤ ty_size (TFn T1 T2 eff) := by
    simpa [ty_size, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TProd left is strictly smaller
/-- ty_size_prod_left (matches Coq) -/
theorem ty_size_prod_left : ∀ T1 T2, ty_size T1 < ty_size (TProd T1 T2) := by
  intro T1 T2
  have h1 : ty_size T1 < ty_size T1 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T1 + 1 ≤ ty_size T1 + 1 + ty_size T2 :=
    Nat.le_add_right _ _
  have h2' : ty_size T1 + 1 ≤ ty_size (TProd T1 T2) := by
    simpa [ty_size, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TProd right is strictly smaller
/-- ty_size_prod_right (matches Coq) -/
theorem ty_size_prod_right : ∀ T1 T2, ty_size T2 < ty_size (TProd T1 T2) := by
  intro T1 T2
  have h1 : ty_size T2 < ty_size T2 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T2 + 1 ≤ ty_size T2 + 1 + ty_size T1 :=
    Nat.le_add_right _ _
  have h2' : ty_size T2 + 1 ≤ ty_size (TProd T1 T2) := by
    simpa [ty_size, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TSum left is strictly smaller
/-- ty_size_sum_left (matches Coq) -/
theorem ty_size_sum_left : ∀ T1 T2, ty_size T1 < ty_size (TSum T1 T2) := by
  intro T1 T2
  have h1 : ty_size T1 < ty_size T1 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T1 + 1 ≤ ty_size T1 + 1 + ty_size T2 :=
    Nat.le_add_right _ _
  have h2' : ty_size T1 + 1 ≤ ty_size (TSum T1 T2) := by
    simpa [ty_size, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TSum right is strictly smaller
/-- ty_size_sum_right (matches Coq) -/
theorem ty_size_sum_right : ∀ T1 T2, ty_size T2 < ty_size (TSum T1 T2) := by
  intro T1 T2
  have h1 : ty_size T2 < ty_size T2 + 1 := Nat.lt_succ_self _
  have h2 : ty_size T2 + 1 ≤ ty_size T2 + 1 + ty_size T1 :=
    Nat.le_add_right _ _
  have h2' : ty_size T2 + 1 ≤ ty_size (TSum T1 T2) := by
    simpa [ty_size, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using h2
  exact Nat.lt_of_lt_of_le h1 h2'

-- TRef content is strictly smaller
/-- ty_size_ref_content (matches Coq) -/
theorem ty_size_ref_content : ∀ T sl, ty_size T < ty_size (TRef T sl) := by
  intro T sl
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TSecret content is strictly smaller
/-- ty_size_secret_content (matches Coq) -/
theorem ty_size_secret_content : ∀ T, ty_size T < ty_size (TSecret T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TProof content is strictly smaller
/-- ty_size_proof_content (matches Coq) -/
theorem ty_size_proof_content : ∀ T, ty_size T < ty_size (TProof T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- ty_size_lt is well-founded (inherits from lt on nat)
/-- ty_size_lt_wf (matches Coq) -/
theorem ty_size_lt_wf : well_founded ty_size_lt := by
  -- well-founded because lt on Nat is well-founded and `ty_size` maps into Nat.
  simpa [well_founded, ty_size_lt] using InvImage.wf ty_size Nat.lt_wfRel.wf

-- Induction principle based on type size
/-- ty_size_induction (matches Coq) -/
theorem ty_size_induction : ∀ (P : ty → Prop), (∀ T, (∀ T', ty_size T' < ty_size T → P T') → P T) → ∀ T, P T := by
  intro P h
  intro T
  refine ty_size_lt_wf.induction T ?_
  intro t ih
  apply h
  intro t' hlt
  exact ih t' hlt

-- First-order types contain no TFn
/-- first_order_no_fn (matches Coq) -/
theorem first_order_no_fn : ∀ T T1 T2 eff, first_order_type T = true → T ≠ TFn T1 T2 eff := by
  intro T T1 T2 eff hfo hEq
  cases hEq
  simp [first_order_type] at hfo

-- First-order is decidable
/-- first_order_decidable (matches Coq) -/
theorem first_order_decidable : ∀ T, (first_order_type T = true) ∨ (first_order_type T = false) := by
  intro T
  cases h : first_order_type T <;> simp [h]

-- First-order subtypes of first-order types
/-- first_order_prod_inv (matches Coq) -/
theorem first_order_prod_inv : ∀ T1 T2, first_order_type (TProd T1 T2) = true → first_order_type T1 = true ∧ first_order_type T2 = true := by
  intro T1 T2 h
  simpa [first_order_type, Bool.and_eq_true] using h

/-- first_order_sum_inv (matches Coq) -/
theorem first_order_sum_inv : ∀ T1 T2, first_order_type (TSum T1 T2) = true → first_order_type T1 = true ∧ first_order_type T2 = true := by
  intro T1 T2 h
  simpa [first_order_type, Bool.and_eq_true] using h

/-- first_order_ref_inv (matches Coq) -/
theorem first_order_ref_inv : ∀ T sl, first_order_type (TRef T sl) = true → first_order_type T = true := by
  intro T sl h
  simpa [first_order_type] using h

/-- first_order_secret_inv (matches Coq) -/
theorem first_order_secret_inv : ∀ T, first_order_type (TSecret T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

/-- first_order_proof_inv (matches Coq) -/
theorem first_order_proof_inv : ∀ T, first_order_type (TProof T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

-- fo_compound_depth for TProd
/-- fo_compound_depth_prod (matches Coq) -/
theorem fo_compound_depth_prod : ∀ T1 T2, fo_compound_depth (TProd T1 T2) = 1 + Nat.max (fo_compound_depth T1) (fo_compound_depth T2) := by
  intro T1 T2
  simpa [fo_compound_depth, Nat.succ_eq_add_one, Nat.add_comm, Nat.add_left_comm]

-- fo_compound_depth for TSum
/-- fo_compound_depth_sum (matches Coq) -/
theorem fo_compound_depth_sum : ∀ T1 T2, fo_compound_depth (TSum T1 T2) = 1 + Nat.max (fo_compound_depth T1) (fo_compound_depth T2) := by
  intro T1 T2
  simpa [fo_compound_depth, Nat.succ_eq_add_one, Nat.add_comm, Nat.add_left_comm]

-- Component depths are less than parent
/-- fo_compound_depth_prod_left (matches Coq) -/
theorem fo_compound_depth_prod_left : ∀ T1 T2, fo_compound_depth T1 < fo_compound_depth (TProd T1 T2) := by
  intro T1 T2
  have h : fo_compound_depth T1 ≤ Nat.max (fo_compound_depth T1) (fo_compound_depth T2) :=
    Nat.le_max_left _ _
  exact Nat.lt_succ_of_le h

/-- fo_compound_depth_prod_right (matches Coq) -/
theorem fo_compound_depth_prod_right : ∀ T1 T2, fo_compound_depth T2 < fo_compound_depth (TProd T1 T2) := by
  intro T1 T2
  have h : fo_compound_depth T2 ≤ Nat.max (fo_compound_depth T1) (fo_compound_depth T2) :=
    Nat.le_max_right _ _
  exact Nat.lt_succ_of_le h

/-- fo_compound_depth_sum_left (matches Coq) -/
theorem fo_compound_depth_sum_left : ∀ T1 T2, fo_compound_depth T1 < fo_compound_depth (TSum T1 T2) := by
  intro T1 T2
  have h : fo_compound_depth T1 ≤ Nat.max (fo_compound_depth T1) (fo_compound_depth T2) :=
    Nat.le_max_left _ _
  exact Nat.lt_succ_of_le h

/-- fo_compound_depth_sum_right (matches Coq) -/
theorem fo_compound_depth_sum_right : ∀ T1 T2, fo_compound_depth T2 < fo_compound_depth (TSum T1 T2) := by
  intro T1 T2
  have h : fo_compound_depth T2 ≤ Nat.max (fo_compound_depth T1) (fo_compound_depth T2) :=
    Nat.le_max_right _ _
  exact Nat.lt_succ_of_le h

-- Primitive and simple types have depth 0
/-- Primitive-type predicate used by `fo_compound_depth_primitive`. -/
def fo_is_primitive : ty → Prop
  | TUnit => True
  | TBool => True
  | TInt => True
  | TString => True
  | TBytes => True
  | TCapability _ => True
  | TCapabilityFull _ => True
  | TChan _ => True
  | TSecureChan _ _ => True
  | _ => False

/-- fo_compound_depth_primitive (matches Coq) -/
theorem fo_compound_depth_primitive : ∀ T, fo_is_primitive T → fo_compound_depth T = 0 := by
  intro T h
  cases T <;> simp [fo_is_primitive, fo_compound_depth] at h ⊢

-- Depth subtype lemmas
/-- ty_depth_fn_arg (matches Coq) -/
theorem ty_depth_fn_arg : ∀ T1 T2 eff, ty_depth T1 < ty_depth (TFn T1 T2 eff) := by
  intro T1 T2 eff
  have h : ty_depth T1 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_left _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

/-- ty_depth_fn_res (matches Coq) -/
theorem ty_depth_fn_res : ∀ T1 T2 eff, ty_depth T2 < ty_depth (TFn T1 T2 eff) := by
  intro T1 T2 eff
  have h : ty_depth T2 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_right _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- First-order types have depth 0 for base types
/-- first_order_base_depth (matches Coq) -/
theorem first_order_base_depth : ∀ T, first_order_type T = true → ty_depth T ≥ 0 := by
  intro T _
  exact Nat.zero_le _

-- TList component is smaller
/-- ty_size_list (matches Coq) -/
theorem ty_size_list : ∀ T, ty_size T < ty_size (TList T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TOption component is smaller
/-- ty_size_option (matches Coq) -/
theorem ty_size_option : ∀ T, ty_size T < ty_size (TOption T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TLabeled component is smaller
/-- ty_size_labeled (matches Coq) -/
theorem ty_size_labeled : ∀ T sl, ty_size T < ty_size (TLabeled T sl) := by
  intro T sl
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TTainted component is smaller
/-- ty_size_tainted (matches Coq) -/
theorem ty_size_tainted : ∀ T sl, ty_size T < ty_size (TTainted T sl) := by
  intro T sl
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TSanitized component is smaller
/-- ty_size_sanitized (matches Coq) -/
theorem ty_size_sanitized : ∀ T sl, ty_size T < ty_size (TSanitized T sl) := by
  intro T sl
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TConstantTime component is smaller
/-- ty_size_constant_time (matches Coq) -/
theorem ty_size_constant_time : ∀ T, ty_size T < ty_size (TConstantTime T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- TZeroizing component is smaller
/-- ty_size_zeroizing (matches Coq) -/
theorem ty_size_zeroizing : ∀ T, ty_size T < ty_size (TZeroizing T) := by
  intro T
  have := Nat.lt_succ_self (ty_size T)
  simpa [ty_size, Nat.add_comm] using this

-- ty_depth for product left
/-- ty_depth_prod_left (matches Coq) -/
theorem ty_depth_prod_left : ∀ T1 T2, ty_depth T1 < ty_depth (TProd T1 T2) := by
  intro T1 T2
  have h : ty_depth T1 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_left _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- ty_depth for product right
/-- ty_depth_prod_right (matches Coq) -/
theorem ty_depth_prod_right : ∀ T1 T2, ty_depth T2 < ty_depth (TProd T1 T2) := by
  intro T1 T2
  have h : ty_depth T2 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_right _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- ty_depth for sum left
/-- ty_depth_sum_left (matches Coq) -/
theorem ty_depth_sum_left : ∀ T1 T2, ty_depth T1 < ty_depth (TSum T1 T2) := by
  intro T1 T2
  have h : ty_depth T1 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_left _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- ty_depth for sum right
/-- ty_depth_sum_right (matches Coq) -/
theorem ty_depth_sum_right : ∀ T1 T2, ty_depth T2 < ty_depth (TSum T1 T2) := by
  intro T1 T2
  have h : ty_depth T2 ≤ Nat.max (ty_depth T1) (ty_depth T2) := Nat.le_max_right _ _
  have := Nat.lt_succ_of_le h
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

/-- first_order_list_inv (matches Coq) -/
theorem first_order_list_inv : ∀ T, first_order_type (TList T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

/-- first_order_option_inv (matches Coq) -/
theorem first_order_option_inv : ∀ T, first_order_type (TOption T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

/-- first_order_labeled_inv (matches Coq) -/
theorem first_order_labeled_inv : ∀ T sl, first_order_type (TLabeled T sl) = true → first_order_type T = true := by
  intro T sl h
  simpa [first_order_type] using h

/-- first_order_constant_time_inv (matches Coq) -/
theorem first_order_constant_time_inv : ∀ T, first_order_type (TConstantTime T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

/-- first_order_zeroizing_inv (matches Coq) -/
theorem first_order_zeroizing_inv : ∀ T, first_order_type (TZeroizing T) = true → first_order_type T = true := by
  intro T h
  simpa [first_order_type] using h

-- Type depth is always non-negative (trivial but useful)
/-- ty_depth_nonneg (matches Coq) -/
theorem ty_depth_nonneg : ∀ T, 0 ≤ ty_depth T := by
  intro T
  exact Nat.zero_le _

-- Function type has strictly positive depth
/-- ty_depth_fn_positive (matches Coq) -/
theorem ty_depth_fn_positive : ∀ T1 T2 ε, ty_depth (TFn T1 T2 ε) > 0 := by
  intro T1 T2 ε
  have : 0 < Nat.succ (Nat.max (ty_depth T1) (ty_depth T2)) := Nat.succ_pos _
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- Product type has strictly positive depth
/-- ty_depth_prod_positive (matches Coq) -/
theorem ty_depth_prod_positive : ∀ T1 T2, ty_depth (TProd T1 T2) > 0 := by
  intro T1 T2
  have : 0 < Nat.succ (Nat.max (ty_depth T1) (ty_depth T2)) := Nat.succ_pos _
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- Sum type has strictly positive depth
/-- ty_depth_sum_positive (matches Coq) -/
theorem ty_depth_sum_positive : ∀ T1 T2, ty_depth (TSum T1 T2) > 0 := by
  intro T1 T2
  have : 0 < Nat.succ (Nat.max (ty_depth T1) (ty_depth T2)) := Nat.succ_pos _
  simpa [ty_depth, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using this

-- Secret type has strictly positive depth
/-- ty_depth_secret_positive (matches Coq) -/
theorem ty_depth_secret_positive : ∀ T, ty_depth (TSecret T) > 0 := by
  intro T
  have : 0 < Nat.succ (ty_depth T) := Nat.succ_pos _
  simpa [ty_depth, Nat.add_comm] using this

end RIINA
