[package]
name = "riina-typechecker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "RIINA type checker"

[dependencies]
riina-types.workspace = true

[dev-dependencies]
riina-parser.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(test)'] }
